import { ref } from 'vue'

export function useRuleAutoName() {
  const isApplyingSystemRuleName = ref(false)
  const isRuleNameManuallyEdited = ref(false)
  const lastAutoGeneratedRuleName = ref('')

  function markSystemRuleNameApplied(ruleName: string): void {
    lastAutoGeneratedRuleName.value = ruleName
  }

  function resetRuleAutoName(): void {
    isApplyingSystemRuleName.value = false
    isRuleNameManuallyEdited.value = false
    lastAutoGeneratedRuleName.value = ''
  }

  return {
    isApplyingSystemRuleName,
    isRuleNameManuallyEdited,
    lastAutoGeneratedRuleName,
    markSystemRuleNameApplied,
    resetRuleAutoName,
  }
}
