<script setup lang="ts">
import { computed, onMounted, reactive, ref, watch } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { Plus, Search } from '@element-plus/icons-vue'

import ResultBoardPanel from '../components/workbench/ResultBoardPanel.vue'
import DataSourcePanel from '../components/workbench/DataSourcePanel.vue'
import VariablePoolPanel from '../components/workbench/VariablePoolPanel.vue'
import DataTable from '../components/shell/DataTable.vue'
import EmptyState from '../components/shell/EmptyState.vue'
import PageHeader from '../components/shell/PageHeader.vue'
import SectionHeader from '../components/shell/SectionHeader.vue'
import StatPill from '../components/shell/StatPill.vue'
import { useFixedRulesStore } from '../store/fixedRules'
import type {
  CompositeAssertionOperator,
  CompositeBranch,
  CompositeCondition,
  CompositeFilterOperator,
  CompositeRuleConfig,
  FixedRuleDefinition,
  FixedRuleOperator,
  FixedRuleSelection,
} from '../types/fixedRules'
import type { DataSource, VariableTag } from '../types/workbench'

type ConditionMode = 'filter' | 'assertion'
type StepIndex = 1 | 2 | 3 | 4
type SectionStatus = 'pending' | 'active' | 'done'

const KEY_FIELD = '__key__'

// 保持原有逻辑不变：固定规则页的配置加载、规则编辑、执行与 SVN 联动均不做业务修改。
const store = useFixedRulesStore()

const isBootstrapping = ref(true)
const isRuleDialogVisible = ref(false)
const ruleDialogMode = ref<'create' | 'edit'>('create')
const isInitializingRuleDialog = ref(false)
const isApplyingSystemRuleName = ref(false)
const isRuleNameManuallyEdited = ref(false)
const lastAutoGeneratedRuleName = ref('')
const dataSourcePanelRef = ref<{ openCreateDialog: () => void } | null>(null)
const variablePoolPanelRef = ref<{
  openSingleCreateTab: () => Promise<void>
  openCompositeCreateTab: () => Promise<void>
} | null>(null)
const selectedGuideStep = ref<StepIndex | null>(null)
const hasManuallySelectedGuideStep = ref(false)
const sourceStepRef = ref<HTMLElement | null>(null)
const variableStepRef = ref<HTMLElement | null>(null)
const ruleStepRef = ref<HTMLElement | null>(null)
const resultStepRef = ref<HTMLElement | null>(null)

const ruleForm = reactive<{
  rule_id: string
  group_id: string
  rule_name: string
  target_variable_tag: string
  selected_rule: FixedRuleSelection
  expected_value: string
  reference_variable_tag: string
}>({
  rule_id: '',
  group_id: 'ungrouped',
  rule_name: '',
  target_variable_tag: '',
  selected_rule: 'gt',
  expected_value: '0',
  reference_variable_tag: '',
})

const compositeRuleForm = reactive<CompositeRuleConfig>({
  global_filters: [],
  branches: [],
})

const ruleSelectionOptions: Array<{ label: string; value: FixedRuleSelection }> = [
  { label: '等于 (=)', value: 'eq' },
  { label: '不等于 (!=)', value: 'ne' },
  { label: '大于 (>)', value: 'gt' },
  { label: '小于 (<)', value: 'lt' },
  { label: '非空校验', value: 'not_null' },
  { label: '唯一校验', value: 'unique' },
  { label: '包含 (in)', value: 'in' },
]

const compositeFilterOptions: Array<{ label: string; value: CompositeFilterOperator }> = [
  { label: '等于 (=)', value: 'eq' },
  { label: '不等于 (!=)', value: 'ne' },
  { label: '大于 (>)', value: 'gt' },
  { label: '小于 (<)', value: 'lt' },
  { label: '非空校验', value: 'not_null' },
]

const compositeAssertionOptions: Array<{ label: string; value: CompositeAssertionOperator }> = [
  { label: '等于 (=)', value: 'eq' },
  { label: '不等于 (!=)', value: 'ne' },
  { label: '大于 (>)', value: 'gt' },
  { label: '小于 (<)', value: 'lt' },
  { label: '非空校验', value: 'not_null' },
  { label: '唯一校验', value: 'unique' },
  { label: '必须重复', value: 'duplicate_required' },
]

const compareRuleSelections = new Set<FixedRuleOperator>(['eq', 'ne', 'gt', 'lt'])
const compositeCompareOperators = new Set<CompositeFilterOperator | CompositeAssertionOperator>([
  'eq',
  'ne',
  'gt',
  'lt',
])
const ruleSelectionNameMap: Record<FixedRuleSelection, string> = {
  eq: '等于',
  ne: '不等于',
  gt: '大于',
  lt: '小于',
  not_null: '非空校验',
  unique: '唯一校验',
  in: '包含',
}
const operatorSymbolMap: Record<FixedRuleOperator, string> = {
  eq: '=',
  ne: '!=',
  gt: '>',
  lt: '<',
}

const invalidRuleIdSet = computed(() => new Set(store.invalidRuleIds))
const invalidGroupIdSet = computed(() => new Set(store.invalidGroupIds))
const variableMap = computed(
  () => new Map(store.variables.map((variable) => [variable.tag, variable] as const)),
)
const sourceMap = computed(
  () => new Map(store.sources.map((source) => [source.id, source] as const)),
)
const variableOptions = computed(() => store.variables)
const singleVariableOptions = computed(() =>
  store.variables.filter((variable) => (variable.variable_kind ?? 'single') === 'single'),
)
const sourceIssueMap = computed(() =>
  store.configIssues.reduce<Record<string, string>>((accumulator, issue) => {
    if (issue.source_id && !accumulator[issue.source_id]) {
      accumulator[issue.source_id] = issue.message
    }
    return accumulator
  }, {}),
)
const configIssueDescription = computed(() =>
  store.configIssues.map((issue) => issue.message).join('；'),
)

const selectedRuleVariable = computed<VariableTag | null>(
  () => variableMap.value.get(ruleForm.target_variable_tag) ?? null,
)
const isCompositeRuleTarget = computed(
  () => (selectedRuleVariable.value?.variable_kind ?? 'single') === 'composite',
)
const referenceVariableOptions = computed(() =>
  singleVariableOptions.value.filter((variable) => variable.tag !== ruleForm.target_variable_tag),
)
const compositeFieldOptions = computed(() => {
  const variable = selectedRuleVariable.value
  if (!variable || (variable.variable_kind ?? 'single') !== 'composite') {
    return [] as Array<{ label: string; value: string }>
  }

  const keyColumn = variable.key_column?.trim() ?? ''
  return [
    {
      label: keyColumn ? `${keyColumn} (Key)` : 'Key(映射键)',
      value: KEY_FIELD,
    },
    ...(variable.columns ?? [])
      .map((column) => column.trim())
      .filter((column) => column && column !== keyColumn)
      .map((column) => ({ label: column, value: column })),
  ]
})

const canCreateRule = computed(() => variableOptions.value.length > 0)

const shouldShowExpectedValue = computed(
  () => !isCompositeRuleTarget.value && isCompareRuleSelection(ruleForm.selected_rule),
)
const shouldShowReferenceVariable = computed(
  () => !isCompositeRuleTarget.value && ruleForm.selected_rule === 'in',
)
const expectedValuePlaceholder = computed(() =>
  ruleForm.selected_rule === 'eq' || ruleForm.selected_rule === 'ne'
    ? '请输入要比较的精确值'
    : '请输入数值阈值',
)

type StatTone = 'pending' | 'active' | 'done' | 'warn' | 'error'

const overviewItems = computed<
  Array<{
    label: string
    value: number
    pendingHint: string
    readyHint: string
    pendingTone: StatTone
    readyTone: StatTone
  }>
>(() => [
  {
    label: '数据源',
    value: store.sourceCount,
    pendingHint: '未接入',
    readyHint: '已接入',
    pendingTone: 'warn',
    readyTone: 'done',
  },
  {
    label: '变量',
    value: store.variableCount,
    pendingHint: '未配置',
    readyHint: '已就绪',
    pendingTone: 'pending',
    readyTone: 'done',
  },
  {
    label: '规则',
    value: store.totalRuleCount,
    pendingHint: '未配置',
    readyHint: '已就绪',
    pendingTone: 'pending',
    readyTone: 'done',
  },
  {
    label: '最近异常',
    value: store.abnormalResults.length,
    pendingHint: '尚未执行',
    readyHint: '需关注',
    pendingTone: 'pending',
    readyTone: 'warn',
  },
])

const stepStatuses = computed<{
  source: SectionStatus
  variable: SectionStatus
  rule: SectionStatus
  result: SectionStatus
}>(() => ({
  source: store.sourceCount ? 'done' : 'active',
  variable: !store.sourceCount ? 'pending' : store.variableCount ? 'done' : 'active',
  rule: !store.variableCount ? 'pending' : store.totalRuleCount ? 'done' : 'active',
  result: !store.totalRuleCount
    ? 'pending'
    : store.executionMeta || store.pageError || store.svnUpdateSummary || store.svnUpdateResults.length
      ? 'done'
      : 'active',
}))

const stepHints = computed(() => ({
  source: store.sourceCount ? `已接入 ${store.sourceCount} 个数据源` : '至少接入 1 个',
  variable: `已沉淀 ${store.variableCount} 个变量`,
  rule: `已编排 ${store.totalRuleCount} 条规则`,
  result: '扫描统计、SVN 输出与异常明细',
}))

const workflowGuide = computed(() => {
  if (!store.sourceCount) {
    return { step: 1 as StepIndex, action: 'scroll' as const }
  }
  if (!store.variableCount) {
    return { step: 2 as StepIndex, action: 'scroll' as const }
  }
  if (!store.totalRuleCount) {
    return { step: 3 as StepIndex, action: 'scroll' as const }
  }
  if (store.isExecuting || store.pageError || store.executionMeta || store.svnUpdateSummary || store.svnUpdateResults.length) {
    return { step: 4 as StepIndex, action: 'scroll' as const }
  }
  return { step: 4 as StepIndex, action: 'execute' as const }
})

const activeGuideStep = computed(() => selectedGuideStep.value ?? workflowGuide.value.step)

const stepperItems = computed(() => [
  {
    step: 1 as StepIndex,
    label: '数据源',
    description: stepHints.value.source,
    status: stepStatuses.value.source,
  },
  {
    step: 2 as StepIndex,
    label: '变量池',
    description: stepHints.value.variable,
    status: stepStatuses.value.variable,
  },
  {
    step: 3 as StepIndex,
    label: '规则',
    description: stepHints.value.rule,
    status: stepStatuses.value.rule,
  },
  {
    step: 4 as StepIndex,
    label: '结果',
    description: stepHints.value.result,
    status: stepStatuses.value.result,
  },
])

const currentGroupCount = computed(
  () => store.groupRuleCounts[store.selectedGroup.group_id] ?? 0,
)
const currentGroupVariableCount = computed(() => {
  const tags = new Set(
    store.currentGroupRules
      .map((rule) => rule.target_variable_tag.trim())
      .filter(Boolean),
  )
  return tags.size
})

const svnResultStats = computed(() => {
  const successCount = store.svnUpdateResults.filter((item) => item.status === 'success').length
  const failedCount = store.svnUpdateResults.length - successCount
  return { successCount, failedCount }
})

watch(
  () => ruleForm.selected_rule,
  (selectedRule) => {
    if (selectedRule === 'in') {
      ruleForm.expected_value = ''
      if (
        ruleForm.reference_variable_tag &&
        !referenceVariableOptions.value.some(
          (variable) => variable.tag === ruleForm.reference_variable_tag,
        )
      ) {
        ruleForm.reference_variable_tag = ''
      }
      syncRuleNameWithForm()
      return
    }

    ruleForm.reference_variable_tag = ''
    if (!isCompareRuleSelection(selectedRule)) {
      ruleForm.expected_value = ''
      syncRuleNameWithForm()
      return
    }

    if (!ruleForm.expected_value.trim() && (selectedRule === 'gt' || selectedRule === 'lt')) {
      ruleForm.expected_value = '0'
    }

    syncRuleNameWithForm()
  },
)

watch(
  [
    () => ruleForm.target_variable_tag,
    () => ruleForm.expected_value,
    () => ruleForm.reference_variable_tag,
  ],
  () => {
    if (
      ruleForm.reference_variable_tag &&
      !referenceVariableOptions.value.some(
        (variable) => variable.tag === ruleForm.reference_variable_tag,
      )
    ) {
      ruleForm.reference_variable_tag = ''
    }
    syncRuleNameWithForm()
  },
)

watch(
  () => ruleForm.rule_name,
  (value) => {
    if (isInitializingRuleDialog.value || isApplyingSystemRuleName.value) {
      return
    }

    const normalizedValue = value.trim()
    if (!normalizedValue) {
      isRuleNameManuallyEdited.value = true
      return
    }

    isRuleNameManuallyEdited.value = normalizedValue !== lastAutoGeneratedRuleName.value
  },
)

onMounted(async () => {
  try {
    // 保留原有业务逻辑：页面初始化仍并行读取能力声明与已保存配置。
    await Promise.all([store.loadCapabilities(), store.loadConfig()])
  } catch {
    // 页面级错误由 store 托管，这里避免重复提示。
  } finally {
    isBootstrapping.value = false
  }
})

watch(
  () => workflowGuide.value.step,
  (step) => {
    if (!hasManuallySelectedGuideStep.value) {
      selectedGuideStep.value = step
    }
  },
  { immediate: true },
)

function getStepRef(step: StepIndex): HTMLElement | null {
  if (step === 1) {
    return sourceStepRef.value
  }
  if (step === 2) {
    return variableStepRef.value
  }
  if (step === 3) {
    return ruleStepRef.value
  }
  return resultStepRef.value
}

async function scrollToStep(step: StepIndex): Promise<void> {
  getStepRef(step)?.scrollIntoView({
    behavior: 'smooth',
    block: 'start',
  })
}

async function handleStepperClick(step: StepIndex): Promise<void> {
  hasManuallySelectedGuideStep.value = true
  selectedGuideStep.value = step
  await scrollToStep(step)
}

function getSectionStatusLabel(step: StepIndex): string {
  if (step === 4) {
    if (store.pageError) {
      return '需关注'
    }
    return store.executionMeta || store.svnUpdateSummary || store.svnUpdateResults.length ? '已完成' : '待执行'
  }

  if (step === 1) {
    return store.sourceCount ? '已完成' : '待配置'
  }

  if (step === 2) {
    return store.variableCount ? '已完成' : '待配置'
  }

  return store.totalRuleCount ? '已完成' : '待配置'
}

function getSectionStatusTone(step: StepIndex): 'pending' | 'done' | 'warn' {
  if (step === 4 && store.pageError) {
    return 'warn'
  }

  return getSectionStatusLabel(step) === '已完成' ? 'done' : 'pending'
}

function isCompareRuleSelection(value: FixedRuleSelection): value is FixedRuleOperator {
  return compareRuleSelections.has(value as FixedRuleOperator)
}

function isCompositeCompareOperator(
  value: CompositeFilterOperator | CompositeAssertionOperator,
): value is FixedRuleOperator {
  return compositeCompareOperators.has(value)
}

function createId(prefix: string): string {
  return `${prefix}-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`
}

function createCondition(): CompositeCondition {
  return {
    condition_id: createId('condition'),
    field: '',
    operator: 'eq',
    value_source: 'literal',
    expected_value: '',
    expected_field: '',
  }
}

function createBranch(): CompositeBranch {
  return {
    branch_id: createId('branch'),
    filters: [],
    assertions: [createCondition()],
  }
}

function normalizeCompositeConfig(config?: CompositeRuleConfig): CompositeRuleConfig {
  return {
    global_filters: (config?.global_filters ?? []).map((condition) => ({
      ...condition,
      condition_id: condition.condition_id || createId('condition'),
    })),
    branches: (config?.branches?.length ? config.branches : [createBranch()]).map((branch) => ({
      branch_id: branch.branch_id || createId('branch'),
      filters: (branch.filters ?? []).map((condition) => ({
        ...condition,
        condition_id: condition.condition_id || createId('condition'),
      })),
      assertions: (branch.assertions?.length ? branch.assertions : [createCondition()]).map((condition) => ({
        ...condition,
        condition_id: condition.condition_id || createId('condition'),
      })),
    })),
  }
}

function applyCompositeConfig(config?: CompositeRuleConfig): void {
  const next = normalizeCompositeConfig(config)
  compositeRuleForm.global_filters = next.global_filters
  compositeRuleForm.branches = next.branches
}

function resetCompositeConfig(): void {
  applyCompositeConfig(undefined)
}

function addGlobalFilter(): void {
  compositeRuleForm.global_filters.push(createCondition())
}

function removeGlobalFilter(conditionId: string): void {
  compositeRuleForm.global_filters = compositeRuleForm.global_filters.filter(
    (condition) => condition.condition_id !== conditionId,
  )
}

function addBranch(): void {
  compositeRuleForm.branches.push(createBranch())
}

function removeBranch(branchId: string): void {
  compositeRuleForm.branches = compositeRuleForm.branches.filter((branch) => branch.branch_id !== branchId)
}

function addBranchFilter(branch: CompositeBranch): void {
  branch.filters.push(createCondition())
}

function removeBranchFilter(branch: CompositeBranch, conditionId: string): void {
  branch.filters = branch.filters.filter((condition) => condition.condition_id !== conditionId)
}

function addBranchAssertion(branch: CompositeBranch): void {
  branch.assertions.push(createCondition())
}

function removeBranchAssertion(branch: CompositeBranch, conditionId: string): void {
  branch.assertions = branch.assertions.filter((condition) => condition.condition_id !== conditionId)
}

function setConditionOperator(
  condition: CompositeCondition,
  operator: CompositeFilterOperator | CompositeAssertionOperator,
): void {
  condition.operator = operator
  if (!isCompositeCompareOperator(operator)) {
    condition.value_source = undefined
    condition.expected_value = undefined
    condition.expected_field = undefined
    return
  }

  if (condition.value_source !== 'field' && condition.value_source !== 'literal') {
    condition.value_source = 'literal'
  }
  if (condition.value_source === 'field') {
    condition.expected_value = undefined
  } else {
    condition.expected_field = undefined
  }
}

function setConditionValueSource(condition: CompositeCondition, valueSource: 'literal' | 'field'): void {
  condition.value_source = valueSource
  if (valueSource === 'field') {
    condition.expected_value = undefined
  } else {
    condition.expected_field = undefined
  }
}

function shouldShowConditionValueSource(condition: CompositeCondition): boolean {
  return isCompositeCompareOperator(condition.operator)
}

function shouldShowConditionExpectedValue(condition: CompositeCondition): boolean {
  return isCompositeCompareOperator(condition.operator) && (condition.value_source ?? 'literal') === 'literal'
}

function shouldShowConditionExpectedField(condition: CompositeCondition): boolean {
  return isCompositeCompareOperator(condition.operator) && condition.value_source === 'field'
}

function getConditionOptions(mode: ConditionMode) {
  return mode === 'filter' ? compositeFilterOptions : compositeAssertionOptions
}

function handleFilterOperatorChange(condition: CompositeCondition, value: string): void {
  setConditionOperator(condition, value as CompositeFilterOperator)
}

function handleAssertionOperatorChange(condition: CompositeCondition, value: string): void {
  setConditionOperator(condition, value as CompositeAssertionOperator)
}

function handleConditionValueSourceChange(condition: CompositeCondition, value: string): void {
  setConditionValueSource(condition, value as 'literal' | 'field')
}

function isKnownCompositeField(field: string): boolean {
  return compositeFieldOptions.value.some((option) => option.value === field)
}

function validateCompositeCondition(
  condition: CompositeCondition,
  mode: ConditionMode,
  label: string,
): string | null {
  if (!condition.field.trim()) {
    return `${label}缺少字段。`
  }
  if (!isKnownCompositeField(condition.field.trim())) {
    return `${label}引用了当前组合变量中不存在的字段。`
  }
  if (mode === 'filter' && (condition.operator === 'unique' || condition.operator === 'duplicate_required')) {
    return `${label}的筛选条件不支持唯一或必须重复。`
  }
  if (!isCompositeCompareOperator(condition.operator)) {
    return null
  }

  if ((condition.value_source ?? 'literal') === 'field') {
    if (!condition.expected_field?.trim()) {
      return `${label}缺少右侧字段。`
    }
    if (!isKnownCompositeField(condition.expected_field.trim())) {
      return `${label}引用了无效的右侧字段。`
    }
    return null
  }

  if (!condition.expected_value?.trim()) {
    return `${label}缺少比较值。`
  }
  if ((condition.operator === 'gt' || condition.operator === 'lt') && Number.isNaN(Number(condition.expected_value))) {
    return `${label}的大于/小于比较值必须是合法数字。`
  }
  return null
}

function getSourcePath(source: DataSource | null | undefined): string {
  if (!source) {
    return ''
  }
  return source.pathOrUrl ?? source.path ?? source.url ?? ''
}

function getCompositeFieldLabel(field: string, variable: VariableTag | null): string {
  if (field !== KEY_FIELD) {
    return field
  }
  return `${variable?.key_column || 'Key'} (Key)`
}

function resolveRuleVariable(rule: FixedRuleDefinition): VariableTag | null {
  return variableMap.value.get(rule.target_variable_tag) ?? null
}

function resolveRuleSource(rule: FixedRuleDefinition): DataSource | null {
  const variable = resolveRuleVariable(rule)
  return variable ? sourceMap.value.get(variable.source_id) ?? null : null
}

function getOperatorLabel(value: FixedRuleOperator): string {
  return operatorSymbolMap[value]
}

function getRuleSelectionLabel(value: FixedRuleSelection): string {
  return ruleSelectionOptions.find((item) => item.value === value)?.label ?? value
}

function getRuleSelectionName(value: FixedRuleSelection): string {
  return ruleSelectionNameMap[value]
}

function getRuleSelectionValue(rule: FixedRuleDefinition): FixedRuleSelection {
  if (rule.rule_type === 'fixed_value_compare') {
    return rule.operator ?? 'gt'
  }
  if (rule.rule_type === 'cross_table_mapping') {
    return 'in'
  }
  return rule.rule_type as FixedRuleSelection
}

function getVariableColumnSummary(variable: VariableTag | null | undefined): string {
  if (!variable) {
    return '未绑定变量'
  }
  if ((variable.variable_kind ?? 'single') === 'composite') {
    return `Key=${variable.key_column || 'Key'}；成员列：${
      (variable.columns ?? [])
        .filter((column) => column !== variable.key_column)
        .join(' / ') || '未配置'
    }`
  }
  return variable.column?.trim() || '未配置列'
}

function buildVariableOptionLabel(variable: VariableTag): string {
  return `${variable.tag} | ${variable.source_id} | ${variable.sheet} | ${getVariableColumnSummary(variable)}`
}

function buildDefaultRuleName(
  variable: VariableTag | null,
  selectedRule: FixedRuleSelection,
  expectedValue: string,
  referenceVariableTag = '',
): string {
  if (!variable) {
    return ''
  }

  const normalizedSheet = variable.sheet.trim()
  if ((variable.variable_kind ?? 'single') === 'composite') {
    return `${normalizedSheet}-${variable.tag}-条件分支校验`
  }
  const normalizedColumn = variable.column?.trim() ?? ''
  if (!normalizedSheet || !normalizedColumn) {
    return ''
  }

  const baseName = `${normalizedSheet}-${normalizedColumn}-${getRuleSelectionName(selectedRule)}`
  if (selectedRule === 'in') {
    const referenceVariable = variableMap.value.get(referenceVariableTag)
    const referenceColumn =
      referenceVariable && (referenceVariable.variable_kind ?? 'single') === 'single'
        ? referenceVariable.column?.trim() || referenceVariable.tag
        : referenceVariableTag.trim()
    return referenceColumn ? `${baseName}+${referenceColumn}` : baseName
  }
  if (!isCompareRuleSelection(selectedRule)) {
    return baseName
  }

  const normalizedExpectedValue = expectedValue.trim()
  return normalizedExpectedValue ? `${baseName}+${normalizedExpectedValue}` : baseName
}

function buildDefaultRuleNameFromForm(): string {
  return buildDefaultRuleName(
    selectedRuleVariable.value,
    ruleForm.selected_rule,
    ruleForm.expected_value,
    ruleForm.reference_variable_tag,
  )
}

function applySystemRuleName(nextRuleName: string): void {
  isApplyingSystemRuleName.value = true
  ruleForm.rule_name = nextRuleName
  lastAutoGeneratedRuleName.value = nextRuleName
  isRuleNameManuallyEdited.value = false
  isApplyingSystemRuleName.value = false
}

function syncRuleNameWithForm(): void {
  if (isInitializingRuleDialog.value || isRuleNameManuallyEdited.value) {
    return
  }

  const nextRuleName = buildDefaultRuleNameFromForm()
  const currentRuleName = ruleForm.rule_name.trim()
  if (!nextRuleName) {
    if (!currentRuleName || currentRuleName === lastAutoGeneratedRuleName.value) {
      applySystemRuleName('')
    }
    return
  }

  if (currentRuleName !== nextRuleName || lastAutoGeneratedRuleName.value !== nextRuleName) {
    applySystemRuleName(nextRuleName)
  }
}

function summarizeCondition(
  condition: CompositeCondition,
  variable: VariableTag | null,
): string {
  const fieldLabel = getCompositeFieldLabel(condition.field, variable)
  if (condition.operator === 'not_null') {
    return `${fieldLabel} 非空`
  }
  if (condition.operator === 'unique') {
    return `${fieldLabel} 唯一`
  }
  if (condition.operator === 'duplicate_required') {
    return `${fieldLabel} 必须重复`
  }

  const operator = {
    eq: '=',
    ne: '!=',
    gt: '>',
    lt: '<',
  }[condition.operator as FixedRuleOperator]
  const expected = condition.value_source === 'field'
    ? getCompositeFieldLabel(condition.expected_field ?? '', variable)
    : condition.expected_value ?? ''
  return `${fieldLabel} ${operator} ${expected}`
}

function buildRuleCondition(rule: FixedRuleDefinition): string {
  const variable = resolveRuleVariable(rule)
  const columnName =
    (variable?.variable_kind ?? 'single') === 'composite'
      ? variable?.tag ?? rule.target_variable_tag
      : variable?.column?.trim() || rule.target_variable_tag
  if (rule.rule_type === 'cross_table_mapping') {
    const referenceVariable = variableMap.value.get(rule.reference_variable_tag?.trim() ?? '')
    const referenceColumn =
      referenceVariable && (referenceVariable.variable_kind ?? 'single') === 'single'
        ? referenceVariable.column?.trim() || rule.reference_variable_tag
        : rule.reference_variable_tag || '未绑定基础字典'
    return `${columnName} 包含于 ${referenceColumn}`
  }
  if (rule.rule_type === 'composite_condition_check') {
    const segments: string[] = []
    if (rule.composite_config?.global_filters.length) {
      segments.push(
        `全局：${rule.composite_config.global_filters
          .map((condition) => summarizeCondition(condition, variable))
          .join(' 且 ')}`,
      )
    }
    rule.composite_config?.branches.forEach((branch, index) => {
      segments.push(
        `分支 ${index + 1}：${
          branch.filters.length
            ? branch.filters.map((condition) => summarizeCondition(condition, variable)).join(' 且 ')
            : '命中全部'
        } => ${branch.assertions.map((condition) => summarizeCondition(condition, variable)).join('，')}`,
      )
    })
    return segments.join('；')
  }
  if (rule.rule_type === 'not_null') {
    return `${columnName} 非空校验`
  }
  if (rule.rule_type === 'unique') {
    return `${columnName} 唯一校验`
  }
  return `${columnName} ${getOperatorLabel(rule.operator ?? 'gt')} ${rule.expected_value ?? ''}`
}

function buildRuleSelectionSummary(rule: FixedRuleDefinition): string {
  if (rule.rule_type === 'composite_condition_check') {
    return '组合变量条件分支校验'
  }
  return getRuleSelectionLabel(getRuleSelectionValue(rule))
}

function buildRuleVariableSummary(rule: FixedRuleDefinition): string {
  const variable = resolveRuleVariable(rule)
  if (!variable) {
    return '目标变量已失效，请重新选择变量。'
  }
  return `${variable.source_id} / ${variable.sheet} / ${getVariableColumnSummary(variable)}`
}

function buildRuleSourcePathSummary(rule: FixedRuleDefinition): string {
  return getSourcePath(resolveRuleSource(rule)) || '当前数据源未记录路径'
}

async function persistConfig(successMessage?: string, silent = true): Promise<boolean> {
  try {
    await store.saveConfig()
    if (!silent && successMessage) {
      ElMessage.success(successMessage)
    }
    return true
  } catch (error) {
    ElMessage.error(error instanceof Error ? error.message : '固定规则配置保存失败。')
    return false
  }
}

async function handlePanelChanged(): Promise<void> {
  if (isBootstrapping.value) {
    return
  }
  await persistConfig(undefined, true)
}

function openDataSourceCreate(): void {
  dataSourcePanelRef.value?.openCreateDialog()
}

function openSingleVariableCreate(): void {
  void variablePoolPanelRef.value?.openSingleCreateTab()
}

function openCompositeVariableCreate(): void {
  void variablePoolPanelRef.value?.openCompositeCreateTab()
}

async function handleCreateGroup(): Promise<void> {
  try {
    const result = await ElMessageBox.prompt('输入新的规则组名称。', '新建规则组', {
      confirmButtonText: '创建',
      cancelButtonText: '取消',
      inputPlaceholder: '例如：基础规则校验',
      inputValidator: (value) => Boolean(value.trim()) || '规则组名称不能为空。',
    })
    store.createGroup(result.value)
    await persistConfig('规则组已创建并保存。', false)
  } catch {
    // 用户取消时不提示。
  }
}

async function handleRenameGroup(): Promise<void> {
  if (store.selectedGroup.builtin) {
    return
  }

  try {
    const result = await ElMessageBox.prompt('修改当前规则组名称。', '编辑规则组', {
      confirmButtonText: '保存',
      cancelButtonText: '取消',
      inputValue: store.selectedGroup.group_name,
      inputValidator: (value) => Boolean(value.trim()) || '规则组名称不能为空。',
    })
    store.renameGroup(store.selectedGroup.group_id, result.value)
    await persistConfig('规则组名称已更新并保存。', false)
  } catch {
    // 用户取消时不提示。
  }
}

async function handleRemoveGroup(): Promise<void> {
  if (store.selectedGroup.builtin) {
    return
  }

  try {
    await ElMessageBox.confirm(
      `删除规则组“${store.selectedGroup.group_name}”后，组内规则会自动迁移到“未分组”。`,
      '删除规则组',
      {
        confirmButtonText: '删除',
        cancelButtonText: '取消',
        type: 'warning',
      },
    )
    store.removeGroup(store.selectedGroup.group_id)
    await persistConfig('规则组已删除，组内规则已迁移到未分组并保存。', false)
  } catch {
    // 用户取消时不提示。
  }
}

function openCreateRuleDialog(): void {
  isInitializingRuleDialog.value = true
  ruleDialogMode.value = 'create'
  ruleForm.rule_id = ''
  ruleForm.group_id = store.selectedGroup.group_id
  ruleForm.rule_name = ''
  ruleForm.target_variable_tag = variableOptions.value[0]?.tag ?? ''
  ruleForm.selected_rule = 'gt'
  ruleForm.expected_value = '0'
  ruleForm.reference_variable_tag = ''
  resetCompositeConfig()
  isRuleNameManuallyEdited.value = false
  lastAutoGeneratedRuleName.value = ''
  isInitializingRuleDialog.value = false
  syncRuleNameWithForm()
  isRuleDialogVisible.value = true
}

function openEditRuleDialog(rule: FixedRuleDefinition): void {
  isInitializingRuleDialog.value = true
  ruleDialogMode.value = 'edit'
  ruleForm.rule_id = rule.rule_id
  ruleForm.group_id = rule.group_id
  ruleForm.rule_name = rule.rule_name
  ruleForm.target_variable_tag = rule.target_variable_tag
  if (rule.rule_type === 'composite_condition_check') {
    ruleForm.selected_rule = 'gt'
    ruleForm.expected_value = ''
    ruleForm.reference_variable_tag = ''
    applyCompositeConfig(rule.composite_config)
  } else {
    ruleForm.selected_rule = getRuleSelectionValue(rule)
    ruleForm.expected_value = rule.rule_type === 'fixed_value_compare' ? rule.expected_value ?? '' : ''
    ruleForm.reference_variable_tag =
      rule.rule_type === 'cross_table_mapping' ? rule.reference_variable_tag ?? '' : ''
    resetCompositeConfig()
  }
  const defaultRuleName = buildDefaultRuleName(
    resolveRuleVariable(rule),
    ruleForm.selected_rule,
    ruleForm.expected_value,
    ruleForm.reference_variable_tag,
  )
  const normalizedRuleName = rule.rule_name.trim()
  isRuleNameManuallyEdited.value =
    Boolean(normalizedRuleName) && normalizedRuleName !== defaultRuleName
  lastAutoGeneratedRuleName.value = defaultRuleName
  if (!normalizedRuleName || normalizedRuleName === defaultRuleName) {
    applySystemRuleName(defaultRuleName)
  }
  isInitializingRuleDialog.value = false
  isRuleDialogVisible.value = true
}

function validateRuleForm(): boolean {
  if (!ruleForm.rule_name.trim()) {
    ElMessage.warning('规则名称不能为空。')
    return false
  }
  if (!ruleForm.target_variable_tag.trim()) {
    ElMessage.warning('请先选择目标变量。')
    return false
  }

  const variable = selectedRuleVariable.value
  if (!variable) {
    ElMessage.warning('当前目标变量不存在，请重新选择。')
    return false
  }

  if ((variable.variable_kind ?? 'single') === 'composite') {
    if (!compositeRuleForm.branches.length) {
      ElMessage.warning('组合变量规则至少需要一个条件分支。')
      return false
    }

    for (let index = 0; index < compositeRuleForm.global_filters.length; index += 1) {
      const error = validateCompositeCondition(
        compositeRuleForm.global_filters[index],
        'filter',
        `全局筛选条件 ${index + 1}`,
      )
      if (error) {
        ElMessage.warning(error)
        return false
      }
    }

    for (let branchIndex = 0; branchIndex < compositeRuleForm.branches.length; branchIndex += 1) {
      const branch = compositeRuleForm.branches[branchIndex]
      if (!branch.assertions.length) {
        ElMessage.warning(`分支 ${branchIndex + 1} 至少需要一条校验条件。`)
        return false
      }
      for (let filterIndex = 0; filterIndex < branch.filters.length; filterIndex += 1) {
        const error = validateCompositeCondition(
          branch.filters[filterIndex],
          'filter',
          `分支 ${branchIndex + 1} 的筛选条件 ${filterIndex + 1}`,
        )
        if (error) {
          ElMessage.warning(error)
          return false
        }
      }
      for (let assertionIndex = 0; assertionIndex < branch.assertions.length; assertionIndex += 1) {
        const error = validateCompositeCondition(
          branch.assertions[assertionIndex],
          'assertion',
          `分支 ${branchIndex + 1} 的校验条件 ${assertionIndex + 1}`,
        )
        if (error) {
          ElMessage.warning(error)
          return false
        }
      }
    }

    return true
  }

  if (!shouldShowExpectedValue.value) {
    if (ruleForm.selected_rule === 'in') {
      const referenceTag = ruleForm.reference_variable_tag.trim()
      if (!referenceTag) {
        ElMessage.warning('请选择基础字典变量。')
        return false
      }
      if (referenceTag === ruleForm.target_variable_tag.trim()) {
        ElMessage.warning('基础字典变量不能与目标变量相同。')
        return false
      }
      if (!referenceVariableOptions.value.some((variable) => variable.tag === referenceTag)) {
        ElMessage.warning('当前基础字典变量不可用，请重新选择。')
        return false
      }
    }
    return true
  }
  if (!ruleForm.expected_value.trim()) {
    ElMessage.warning('请填写比较值。')
    return false
  }
  if (
    (ruleForm.selected_rule === 'gt' || ruleForm.selected_rule === 'lt') &&
    Number.isNaN(Number(ruleForm.expected_value))
  ) {
    ElMessage.warning('大于/小于规则的比较值必须是合法数字。')
    return false
  }

  return true
}

async function handleSaveRule(): Promise<void> {
  if (!validateRuleForm()) {
    return
  }

  if (isCompositeRuleTarget.value) {
    store.upsertRule({
      rule_id: ruleForm.rule_id || undefined,
      group_id: ruleForm.group_id,
      rule_name: ruleForm.rule_name,
      target_variable_tag: ruleForm.target_variable_tag,
      rule_type: 'composite_condition_check',
      composite_config: normalizeCompositeConfig(compositeRuleForm),
    })
  } else {
    const selectedRule = ruleForm.selected_rule
    if (isCompareRuleSelection(selectedRule)) {
      store.upsertRule({
        rule_id: ruleForm.rule_id || undefined,
        group_id: ruleForm.group_id,
        rule_name: ruleForm.rule_name,
        target_variable_tag: ruleForm.target_variable_tag,
        rule_type: 'fixed_value_compare',
        operator: selectedRule,
        expected_value: ruleForm.expected_value,
      })
    } else if (selectedRule === 'in') {
      store.upsertRule({
        rule_id: ruleForm.rule_id || undefined,
        group_id: ruleForm.group_id,
        rule_name: ruleForm.rule_name,
        target_variable_tag: ruleForm.target_variable_tag,
        rule_type: 'cross_table_mapping',
        reference_variable_tag: ruleForm.reference_variable_tag,
      })
    } else {
      store.upsertRule({
        rule_id: ruleForm.rule_id || undefined,
        group_id: ruleForm.group_id,
        rule_name: ruleForm.rule_name,
        target_variable_tag: ruleForm.target_variable_tag,
        rule_type: selectedRule,
      })
    }
  }

  const success = await persistConfig(
    ruleDialogMode.value === 'create' ? '规则已创建并保存。' : '规则已更新并保存。',
    false,
  )
  if (success) {
    isRuleDialogVisible.value = false
  }
}

async function handleRemoveRule(rule: FixedRuleDefinition): Promise<void> {
  try {
    await ElMessageBox.confirm(`确认删除规则“${rule.rule_name}”？`, '删除规则', {
      confirmButtonText: '删除',
      cancelButtonText: '取消',
      type: 'warning',
    })
    store.removeRule(rule.rule_id)
    await persistConfig('规则已删除并保存。', false)
  } catch {
    // 用户取消时不提示。
  }
}

async function handleSaveConfig(): Promise<void> {
  await persistConfig('固定规则配置已保存。', false)
}

async function handleExecute(): Promise<void> {
  try {
    // 保留原有业务逻辑：固定规则执行仍走原有 executeConfig 链路与结果消费模型。
    await store.executeConfig()
    await scrollToStep(4)
    if (store.abnormalResults.length) {
      ElMessage.warning(`执行完成，发现 ${store.abnormalResults.length} 条异常结果。`)
      return
    }
    ElMessage.success('执行完成，当前没有命中异常。')
  } catch {
    // 页面级错误由 store 托管。
    await scrollToStep(4)
  }
}

async function handleSvnUpdate(): Promise<void> {
  try {
    // 保留原有业务逻辑：SVN 更新继续复用原有工作副本更新接口。
    await store.runSvnUpdate()
    await scrollToStep(4)
    ElMessage.success(store.svnUpdateSummary || 'SVN 更新完成。')
  } catch {
    // 页面级错误由 store 托管。
    await scrollToStep(4)
  }
}
</script>

<template>
  <div class="flex h-full flex-col bg-canvas font-sans text-ink-700">
    <!-- TopBar -->
    <PageHeader breadcrumb="主菜单 / 固定规则" title="固定规则">
      <template #actions>
        <button
          type="button"
          class="ec-btn ec-btn-secondary"
          :disabled="store.isSaving"
          @click="handleSaveConfig"
        >
          {{ store.isSaving ? '保存中…' : '保存配置' }}
        </button>
        <button
          type="button"
          class="ec-btn ec-btn-secondary"
          :disabled="store.isUpdatingSvn || !store.canRunSvnUpdate"
          @click="handleSvnUpdate"
        >
          {{ store.isUpdatingSvn ? 'SVN 更新中…' : 'SVN 更新' }}
        </button>
        <button
          type="button"
          class="ec-btn ec-btn-primary"
          :disabled="store.isExecuting || !store.canExecute"
          @click="handleExecute"
        >
          <svg class="h-4 w-4" viewBox="0 0 24 24" fill="currentColor">
            <path d="M8 5v14l11-7z" />
          </svg>
          {{ store.isExecuting ? '执行中…' : '执行全部规则' }}
        </button>
      </template>
    </PageHeader>

    <!-- 主滚动区 -->
    <div
      v-loading="isBootstrapping || store.isLoading"
      class="flex-1 overflow-y-auto px-8 py-8 flex flex-col gap-6"
    >
      <!-- Stepper -->
      <section aria-label="进度" class="rounded-card border border-line bg-card px-6 py-5 shadow-card-1">
        <div class="flex items-center gap-4">
          <template v-for="(item, index) in stepperItems" :key="item.step">
            <button
              type="button"
              class="flex appearance-none items-center gap-3 border-0 bg-transparent p-0 text-left shadow-none transition"
              @click="handleStepperClick(item.step)"
            >
              <span
                class="inline-flex h-7 w-7 shrink-0 items-center justify-center rounded-full font-mono text-[12px] font-semibold transition"
                :class="
                  item.step === activeGuideStep
                    ? 'bg-accent text-white'
                    : item.status === 'done'
                      ? 'bg-success text-white'
                      : 'bg-canvas text-ink-500 ring-1 ring-line'
                "
              >
                {{ item.step }}
              </span>
              <div class="min-w-0">
                <div
                  class="text-[14px] font-semibold transition"
                  :class="item.step === activeGuideStep ? 'text-ink-900' : 'text-ink-700'"
                >
                  {{ item.label }}
                </div>
                <div
                  class="max-w-[220px] truncate text-[12px] transition"
                  :class="item.step === activeGuideStep ? 'text-accent-ink' : 'text-ink-500'"
                >
                  {{ item.description }}
                </div>
              </div>
            </button>
            <div
              v-if="index < stepperItems.length - 1"
              class="h-px flex-1 transition"
              :class="item.status === 'done' ? 'bg-accent' : 'bg-line'"
            ></div>
          </template>
        </div>
      </section>

      <!-- KPI -->
      <section aria-label="概览" class="grid grid-cols-4 gap-4">
        <!-- 保留原有业务逻辑：固定规则概览仍基于 overviewItems 计算结果遍历 -->
        <StatPill
          v-for="item in overviewItems"
          :key="item.label"
          :label="item.label"
          :value="item.value"
          :status-label="item.value > 0 ? item.readyHint : item.pendingHint"
          :status-tone="item.value > 0 ? item.readyTone : item.pendingTone"
        />
      </section>

      <!-- Banners：极简告警条（border + 4px 左色带 + 浅底） -->
      <div
        v-if="store.pageError"
        role="alert"
        class="rounded-card border border-line border-l-4 border-l-danger bg-danger-soft/40 px-5 py-3 text-[13px] text-ink-700"
      >
        {{ store.pageError }}
      </div>

      <div
        v-if="store.configIssues.length"
        role="alert"
        class="rounded-card border border-line border-l-4 border-l-warning bg-warning-soft/40 px-5 py-3"
      >
        <div class="text-[13px] font-medium text-ink-900">存在待修复配置</div>
        <div class="mt-1 text-[12px] text-ink-500">{{ configIssueDescription }}</div>
      </div>

      <div
        v-if="store.invalidRuleIds.length"
        role="alert"
        class="rounded-card border border-line border-l-4 border-l-warning bg-warning-soft/40 px-5 py-3"
      >
        <div class="text-[13px] font-medium text-ink-900">存在待修复规则</div>
        <div class="mt-1 text-[12px] text-ink-500">补齐目标变量、规则名、比较值或分支配置后才能执行。</div>
      </div>

      <!-- 数据源 -->
      <section ref="sourceStepRef" class="rounded-card border border-line bg-card shadow-card-1">
        <div class="border-t-2 px-5 py-4" :class="activeGuideStep === 1 ? 'border-accent' : 'border-transparent'">
          <div class="flex items-start justify-between gap-4 border-b border-line pb-3">
            <SectionHeader
              variant="workbench"
              step="01"
              title="数据源"
              description="接入 Excel、CSV、飞书或 SVN 来源"
              :status-label="getSectionStatusLabel(1)"
              :status-tone="getSectionStatusTone(1)"
            />
            <div class="workbench-section-toolbar__actions shrink-0">
              <button
                type="button"
                class="ec-btn-outline-compact"
                @click="openDataSourceCreate"
              >
                <svg class="ec-btn-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                  <path d="M12 5v14M5 12h14" />
                </svg>
                新增数据源
              </button>
              <button
                type="button"
                class="ec-btn-text-collapse"
                aria-disabled="true"
              >
                收起
                <svg class="ec-btn-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                  <path d="m18 15-6-6-6 6" />
                </svg>
              </button>
            </div>
          </div>
          <div class="pt-1">
            <DataSourcePanel
              ref="dataSourcePanelRef"
              :store="store"
              variant="fixed-rules"
              toolbar-mode="hidden"
              :source-issues="sourceIssueMap"
              @changed="handlePanelChanged"
            />
          </div>
        </div>
      </section>

      <!-- 变量池 -->
      <section ref="variableStepRef" class="rounded-card border border-line bg-card shadow-card-1">
        <div class="border-t-2 px-5 py-4" :class="activeGuideStep === 2 ? 'border-accent' : 'border-transparent'">
          <div class="flex items-start justify-between gap-4 border-b border-line pb-3">
            <SectionHeader
              variant="workbench"
              step="02"
              title="变量池"
              description="沉淀后续规则编排会复用的字段与组合变量"
              :status-label="getSectionStatusLabel(2)"
              :status-tone="getSectionStatusTone(2)"
            />
            <div class="workbench-section-toolbar__actions shrink-0">
              <button
                type="button"
                class="ec-btn-outline-compact"
                :disabled="!store.sources.length"
                @click="openSingleVariableCreate"
              >
                添加单个变量
              </button>
              <button
                type="button"
                class="ec-btn-outline-compact"
                :disabled="!store.sources.length"
                @click="openCompositeVariableCreate"
              >
                添加组合变量
              </button>
            </div>
          </div>
          <div class="pt-1">
            <VariablePoolPanel
              ref="variablePoolPanelRef"
              :store="store"
              variant="fixed-rules"
              toolbar-mode="hidden"
              @changed="handlePanelChanged"
            />
          </div>
        </div>
      </section>

      <!-- 规则 -->
      <section ref="ruleStepRef" class="rounded-card border border-line bg-card shadow-card-1">
        <div class="border-t-2 px-5 py-4" :class="activeGuideStep === 3 ? 'border-accent' : 'border-transparent'">
          <div class="flex items-start justify-between gap-4 border-b border-line pb-3">
            <SectionHeader
              variant="workbench"
              step="03"
              title="规则"
              description="按组组织比较、非空、唯一和组合变量规则"
              :status-label="getSectionStatusLabel(3)"
              :status-tone="getSectionStatusTone(3)"
            />
          </div>

          <div class="pt-3">
            <div class="workbench-rule-shell">
              <div class="workbench-rule-layout">
                <!-- 左侧规则组列表 -->
                <aside class="workbench-rule-sidebar">
                  <div class="workbench-rule-sidebar-toolbar">
                    <el-input
                      v-model="store.groupKeyword"
                      placeholder="搜索规则组"
                      :prefix-icon="Search"
                      clearable
                      size="default"
                    />
                    <button
                      type="button"
                      class="ec-btn ec-btn-secondary ec-btn-sm shrink-0"
                      @click="handleCreateGroup"
                    >
                      <Plus class="h-3 w-3" />
                      新建
                    </button>
                  </div>

                  <nav class="workbench-rule-menu">
                    <!-- 保留原有业务逻辑：规则组导航仍基于 store.filteredGroups 遍历并复用原选中逻辑 -->
                    <button
                      v-for="group in store.filteredGroups"
                      :key="group.group_id"
                      type="button"
                      class="workbench-rule-menu-item"
                      :class="group.group_id === store.selectedGroup.group_id ? 'is-active' : ''"
                      @click="store.setSelectedGroup(group.group_id)"
                    >
                      <span class="workbench-rule-menu-item__label">{{ group.group_name }}</span>
                      <span
                        v-if="invalidGroupIdSet.has(group.group_id)"
                        class="workbench-rule-menu-item__dot"
                        title="待修复"
                      ></span>
                      <span class="workbench-rule-menu-item__count">
                        {{ store.groupRuleCounts[group.group_id] ?? 0 }}
                      </span>
                    </button>
                  </nav>
                </aside>

                <!-- 右侧规则区 -->
                <div class="workbench-rule-main">
                  <div class="workbench-rule-header">
                    <div class="min-w-0">
                      <div class="truncate text-[14px] font-semibold text-ink-900">
                        {{ store.selectedGroup.group_name }}
                      </div>
                      <div class="text-[12px] text-ink-500">
                        共 {{ currentGroupCount }} 条规则 · {{ currentGroupVariableCount }} 个变量
                      </div>
                    </div>
                    <div class="workbench-rule-header__actions">
                      <button
                        type="button"
                        class="ec-btn ec-btn-secondary ec-btn-sm"
                        :disabled="store.selectedGroup.builtin"
                        @click="handleRenameGroup"
                      >
                        重命名
                      </button>
                      <button
                        type="button"
                        class="ec-btn ec-btn-secondary ec-btn-sm"
                        :disabled="store.selectedGroup.builtin"
                        @click="handleRemoveGroup"
                      >
                        删除组
                      </button>
                      <button
                        type="button"
                        class="ec-btn ec-btn-primary ec-btn-sm"
                        :disabled="!canCreateRule"
                        @click="openCreateRuleDialog"
                      >
                        <Plus class="h-3.5 w-3.5" />
                        新增规则
                      </button>
                    </div>
                  </div>

                  <DataTable aria-label="固定规则列表">
                    <template #head>
                      <tr>
                        <th class="w-[28%]">规则名称</th>
                        <th>目标变量</th>
                        <th class="w-[20%]">规则选择</th>
                        <th class="w-[20%] text-left align-middle">操作</th>
                      </tr>
                    </template>
                    <template #body>
                      <tr v-if="!canCreateRule">
                        <td colspan="4" class="bg-card">
                          <EmptyState title="请先在上方变量池添加变量" description="至少需要一个变量后才能开始新增规则。">
                            <template #icon>
                              <svg class="h-4 w-4 text-ink-500" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                                <path d="M9 12h6 M12 9v6 M5 5h14v14H5z" />
                              </svg>
                            </template>
                          </EmptyState>
                        </td>
                      </tr>
                      <tr v-else-if="!store.currentGroupRules.length">
                        <td colspan="4" class="bg-card">
                          <EmptyState title="当前组还没有规则" description="点击右上角“新增规则”开始编排。">
                            <template #icon>
                              <Plus class="h-4 w-4 text-ink-500" />
                            </template>
                          </EmptyState>
                        </td>
                      </tr>
                      <template v-else>
                        <tr
                          v-for="row in store.pagedCurrentGroupRules"
                          :key="row.rule_id"
                          class="bg-card text-ink-700"
                        >
                          <td class="align-top">
                            <div
                              class="truncate font-medium"
                              :class="invalidRuleIdSet.has(row.rule_id) ? 'text-danger' : 'text-ink-900'"
                            >
                              {{ row.rule_name }}
                            </div>
                            <div class="mt-1 line-clamp-2 text-[12px] text-ink-500">{{ buildRuleCondition(row) }}</div>
                          </td>
                          <td class="align-top">
                            <div class="truncate font-mono text-[12px] text-ink-900">{{ row.target_variable_tag }}</div>
                            <div class="mt-1 truncate text-[12px] text-ink-500">{{ buildRuleVariableSummary(row) }}</div>
                            <div class="truncate text-[11px] text-ink-500">{{ buildRuleSourcePathSummary(row) }}</div>
                          </td>
                          <td class="align-top">
                            <div class="text-ink-700">{{ buildRuleSelectionSummary(row) }}</div>
                            <div class="mt-1 font-mono text-[12px] text-ink-500">
                              <template v-if="row.rule_type === 'fixed_value_compare'">{{ row.expected_value }}</template>
                              <template v-else-if="row.rule_type === 'cross_table_mapping'">
                                {{ row.reference_variable_tag || '未绑定基础字典' }}
                              </template>
                              <template v-else-if="row.rule_type === 'composite_condition_check'">
                                {{ row.composite_config?.branches.length ?? 0 }} 个分支
                              </template>
                              <template v-else>—</template>
                            </div>
                          </td>
                          <td class="text-left align-top">
                            <div class="table-actions">
                              <button
                                type="button"
                                class="ec-action-link"
                                @click="openEditRuleDialog(row)"
                              >
                                编辑
                              </button>
                              <button
                                type="button"
                                class="ec-action-link-danger"
                                @click="handleRemoveRule(row)"
                              >
                                删除
                              </button>
                            </div>
                          </td>
                        </tr>
                      </template>
                    </template>
                  </DataTable>

                  <div
                    v-if="store.currentGroupRuleTotal > 20"
                    class="flex items-center justify-between gap-3 pt-2"
                  >
                    <span class="text-[12px] text-ink-500">
                      第 {{ store.currentPage }} 页 / 共 {{ store.currentGroupRuleTotal }} 条
                    </span>
                    <el-pagination
                      layout="prev, pager, next"
                      :page-size="20"
                      :total="store.currentGroupRuleTotal"
                      :current-page="store.currentPage"
                      @current-change="store.setCurrentPage"
                    />
                  </div>

                  <div class="mt-6 flex justify-end">
                    <button
                      type="button"
                      class="ec-btn ec-btn-primary"
                      :disabled="store.isExecuting || !store.canExecute"
                      @click="handleExecute"
                    >
                      <svg class="h-4 w-4" viewBox="0 0 24 24" fill="currentColor">
                        <path d="M8 5v14l11-7z" />
                      </svg>
                      {{ store.isExecuting ? '执行中…' : '执行全部规则' }}
                    </button>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      <!-- 执行结果 -->
      <section ref="resultStepRef" class="rounded-card border border-line bg-card shadow-card-1">
        <div class="border-t-2 px-5 py-4" :class="activeGuideStep === 4 ? 'border-accent' : 'border-transparent'">
          <div class="flex items-start justify-between gap-4 border-b border-line pb-4">
            <SectionHeader
              variant="workbench"
              step="04"
              title="结果"
              description="查看扫描统计、SVN 输出和异常明细"
              :status-label="getSectionStatusLabel(4)"
              :status-tone="getSectionStatusTone(4)"
            />
          </div>

          <div class="pt-4">
            <ResultBoardPanel :store="store" :rule-count="store.totalRuleCount">
              <template #extra>
                <div
                  v-if="store.svnUpdateSummary"
                  class="rounded-card border border-line border-l-4 border-l-accent bg-accent-soft/40 px-5 py-3"
                >
                  <div class="text-[13px] font-medium text-ink-900">{{ store.svnUpdateSummary }}</div>
                  <div class="mt-1 text-[12px] text-ink-500">
                    成功 {{ svnResultStats.successCount }} 个，失败 {{ svnResultStats.failedCount }} 个
                  </div>
                </div>

                <div v-if="store.svnUpdateResults.length" class="flex flex-col gap-2">
                  <article
                    v-for="item in store.svnUpdateResults"
                    :key="item.working_copy"
                    class="rounded-field border border-line px-4 py-3"
                    :class="item.status === 'error' ? 'border-l-4 border-l-danger bg-danger-soft/30' : 'bg-canvas'"
                  >
                    <div class="truncate font-mono text-[12px] text-ink-900">{{ item.working_copy }}</div>
                    <div class="mt-1 text-[12px]" :class="item.status === 'error' ? 'text-danger' : 'text-success'">
                      {{ item.status === 'success' ? '更新成功' : '更新失败' }}
                    </div>
                    <div class="mt-1 whitespace-pre-wrap break-all text-[12px] text-ink-500">
                      {{ item.output || item.error || '无额外输出' }}
                    </div>
                  </article>
                </div>
              </template>
            </ResultBoardPanel>
          </div>
        </div>
      </section>
    </div>

    <!-- 新增/编辑规则弹窗 -->
    <el-dialog
      v-model="isRuleDialogVisible"
      width="780px"
      :title="ruleDialogMode === 'create' ? '新增规则' : '编辑规则'"
    >
      <div class="flex flex-col gap-6">
        <!-- 段 1：基本信息 -->
        <section class="flex flex-col gap-3">
          <SectionHeader title="基本信息" description="规则归属、命名与目标变量" />
          <div class="grid grid-cols-2 gap-4">
            <div>
              <label class="mb-1.5 block text-[12px] font-medium text-ink-500">规则组</label>
              <el-select v-model="ruleForm.group_id" class="w-full">
                <el-option
                  v-for="group in store.allGroups"
                  :key="group.group_id"
                  :label="group.group_name"
                  :value="group.group_id"
                />
              </el-select>
            </div>
            <div>
              <label class="mb-1.5 block text-[12px] font-medium text-ink-500">规则名称</label>
              <el-input
                v-model="ruleForm.rule_name"
                placeholder="例如：items-INT_ID-大于+0"
              />
            </div>
          </div>
          <div>
            <label class="mb-1.5 block text-[12px] font-medium text-ink-500">目标变量</label>
            <el-select
              v-model="ruleForm.target_variable_tag"
              class="w-full"
              filterable
              placeholder="选择目标变量"
            >
              <el-option
                v-for="variable in variableOptions"
                :key="variable.tag"
                :label="buildVariableOptionLabel(variable)"
                :value="variable.tag"
              />
            </el-select>
            <div class="mt-2 text-[12px] text-ink-500">
              <span v-if="selectedRuleVariable">
                {{ selectedRuleVariable.source_id }} · {{ selectedRuleVariable.sheet }} · {{
                  (selectedRuleVariable.variable_kind ?? 'single') === 'composite'
                    ? getVariableColumnSummary(selectedRuleVariable)
                    : selectedRuleVariable.column
                }}
              </span>
              <span v-else>请先选择目标变量</span>
            </div>
          </div>
        </section>

        <!-- 段 2：校验配置（单变量） -->
        <section v-if="!isCompositeRuleTarget" class="flex flex-col gap-3">
          <SectionHeader title="校验配置" description="选择规则类型，必要时填写比较值" />
          <div class="grid grid-cols-2 gap-4">
            <div>
              <label class="mb-1.5 block text-[12px] font-medium text-ink-500">规则选择</label>
              <el-select v-model="ruleForm.selected_rule" class="w-full">
                <el-option
                  v-for="option in ruleSelectionOptions"
                  :key="option.value"
                  :label="option.label"
                  :value="option.value"
                />
              </el-select>
            </div>
            <div v-if="shouldShowExpectedValue">
              <label class="mb-1.5 block text-[12px] font-medium text-ink-500">比较值</label>
              <el-input v-model="ruleForm.expected_value" :placeholder="expectedValuePlaceholder" />
            </div>
            <div v-else-if="shouldShowReferenceVariable">
              <label class="mb-1.5 block text-[12px] font-medium text-ink-500">比较值</label>
              <el-select
                v-model="ruleForm.reference_variable_tag"
                class="w-full"
                filterable
                clearable
                :disabled="!referenceVariableOptions.length"
                placeholder="选择基础字典变量"
              >
                <el-option
                  v-for="variable in referenceVariableOptions"
                  :key="variable.tag"
                  :label="buildVariableOptionLabel(variable)"
                  :value="variable.tag"
                />
              </el-select>
            </div>
          </div>
        </section>

        <!-- 段 3：组合分支（组合变量） -->
        <section v-else class="flex flex-col gap-4">
          <SectionHeader title="组合分支" description="先做全局筛选，再按分支匹配 + 校验" />

          <!-- 全局筛选 -->
          <div class="rounded-field bg-subtle p-4">
            <div class="flex items-center justify-between">
              <div class="text-[13px] font-medium text-ink-900">全局筛选条件</div>
              <button
                type="button"
                class="inline-flex items-center gap-1 rounded-field border border-line bg-card px-2.5 py-1.5 text-[12px] text-ink-700 transition hover:border-ink-300"
                @click="addGlobalFilter"
              >
                <Plus class="h-3 w-3" /> 添加全局条件
              </button>
            </div>
            <div v-if="!compositeRuleForm.global_filters.length" class="mt-3 text-[12px] text-ink-500">
              暂无全局条件
            </div>
            <div
              v-for="(condition, index) in compositeRuleForm.global_filters"
              :key="condition.condition_id"
              class="mt-3 rounded-field border border-line bg-card p-4"
            >
              <div class="mb-3 flex items-center justify-between">
                <span class="text-[12px] font-medium text-ink-700">全局条件 {{ index + 1 }}</span>
                <button
                  type="button"
                  class="ec-btn-link-danger"
                  @click="removeGlobalFilter(condition.condition_id)"
                >
                  删除
                </button>
              </div>
              <div class="grid grid-cols-2 gap-3">
                <div>
                  <label class="mb-1 block text-[12px] text-ink-500">字段</label>
                  <el-select v-model="condition.field" class="w-full">
                    <el-option
                      v-for="field in compositeFieldOptions"
                      :key="field.value"
                      :label="field.label"
                      :value="field.value"
                    />
                  </el-select>
                </div>
                <div>
                  <label class="mb-1 block text-[12px] text-ink-500">筛选条件</label>
                  <el-select
                    :model-value="condition.operator"
                    class="w-full"
                    @change="handleFilterOperatorChange(condition, $event)"
                  >
                    <el-option
                      v-for="option in getConditionOptions('filter')"
                      :key="option.value"
                      :label="option.label"
                      :value="option.value"
                    />
                  </el-select>
                </div>
                <div v-if="shouldShowConditionValueSource(condition)">
                  <label class="mb-1 block text-[12px] text-ink-500">右值来源</label>
                  <el-select
                    :model-value="condition.value_source ?? 'literal'"
                    class="w-full"
                    @change="handleConditionValueSourceChange(condition, $event)"
                  >
                    <el-option label="固定值" value="literal" />
                    <el-option label="字段" value="field" />
                  </el-select>
                </div>
                <div v-if="shouldShowConditionExpectedValue(condition)">
                  <label class="mb-1 block text-[12px] text-ink-500">比较值</label>
                  <el-input v-model="condition.expected_value" placeholder="请输入比较值" />
                </div>
                <div v-if="shouldShowConditionExpectedField(condition)">
                  <label class="mb-1 block text-[12px] text-ink-500">右侧字段</label>
                  <el-select v-model="condition.expected_field" class="w-full">
                    <el-option
                      v-for="field in compositeFieldOptions"
                      :key="field.value"
                      :label="field.label"
                      :value="field.value"
                    />
                  </el-select>
                </div>
              </div>
            </div>
          </div>

          <!-- 分支列表 -->
          <div class="flex items-center justify-between">
            <div class="text-[13px] font-medium text-ink-900">条件分支</div>
            <button
              type="button"
              class="inline-flex items-center gap-1 rounded-field bg-accent px-3 py-1.5 text-[12px] font-semibold text-white transition hover:bg-accent-ink"
              @click="addBranch"
            >
              <Plus class="h-3 w-3" /> 添加分支
            </button>
          </div>

          <div
            v-for="(branch, branchIndex) in compositeRuleForm.branches"
            :key="branch.branch_id"
            class="rounded-field border border-line bg-subtle p-4"
          >
            <div class="mb-3 flex items-center justify-between">
              <div class="text-[13px] font-medium text-ink-900">分支 {{ branchIndex + 1 }}</div>
              <button
                type="button"
                class="ec-btn-link-danger"
                @click="removeBranch(branch.branch_id)"
              >
                删除分支
              </button>
            </div>

            <!-- 分支筛选 -->
            <div class="rounded-field bg-card p-4">
              <div class="mb-3 flex items-center justify-between">
                <div class="text-[12px] font-medium text-ink-700">分支筛选条件</div>
                <button
                  type="button"
                  class="inline-flex items-center gap-1 rounded-field border border-line px-2 py-1 text-[12px] text-ink-700 transition hover:border-ink-300"
                  @click="addBranchFilter(branch)"
                >
                  <Plus class="h-3 w-3" /> 添加筛选
                </button>
              </div>
              <div v-if="!branch.filters.length" class="text-[12px] text-ink-500">
                暂无分支筛选条件，命中所有记录
              </div>
              <div
                v-for="(condition, filterIndex) in branch.filters"
                :key="condition.condition_id"
                class="mt-3 rounded-field border border-line p-3"
              >
                <div class="mb-2 flex items-center justify-between">
                  <span class="text-[12px] text-ink-700">筛选条件 {{ filterIndex + 1 }}</span>
                  <button
                    type="button"
                    class="ec-btn-link-danger"
                    @click="removeBranchFilter(branch, condition.condition_id)"
                  >
                    删除
                  </button>
                </div>
                <div class="grid grid-cols-2 gap-3">
                  <div>
                    <label class="mb-1 block text-[12px] text-ink-500">字段</label>
                    <el-select v-model="condition.field" class="w-full">
                      <el-option
                        v-for="field in compositeFieldOptions"
                        :key="field.value"
                        :label="field.label"
                        :value="field.value"
                      />
                    </el-select>
                  </div>
                  <div>
                    <label class="mb-1 block text-[12px] text-ink-500">筛选条件</label>
                    <el-select
                      :model-value="condition.operator"
                      class="w-full"
                      @change="handleFilterOperatorChange(condition, $event)"
                    >
                      <el-option
                        v-for="option in getConditionOptions('filter')"
                        :key="option.value"
                        :label="option.label"
                        :value="option.value"
                      />
                    </el-select>
                  </div>
                  <div v-if="shouldShowConditionValueSource(condition)">
                    <label class="mb-1 block text-[12px] text-ink-500">右值来源</label>
                    <el-select
                      :model-value="condition.value_source ?? 'literal'"
                      class="w-full"
                      @change="handleConditionValueSourceChange(condition, $event)"
                    >
                      <el-option label="固定值" value="literal" />
                      <el-option label="字段" value="field" />
                    </el-select>
                  </div>
                  <div v-if="shouldShowConditionExpectedValue(condition)">
                    <label class="mb-1 block text-[12px] text-ink-500">比较值</label>
                    <el-input v-model="condition.expected_value" placeholder="请输入比较值" />
                  </div>
                  <div v-if="shouldShowConditionExpectedField(condition)">
                    <label class="mb-1 block text-[12px] text-ink-500">右侧字段</label>
                    <el-select v-model="condition.expected_field" class="w-full">
                      <el-option
                        v-for="field in compositeFieldOptions"
                        :key="field.value"
                        :label="field.label"
                        :value="field.value"
                      />
                    </el-select>
                  </div>
                </div>
              </div>
            </div>

            <!-- 分支校验 -->
            <div class="mt-4 rounded-field bg-card p-4">
              <div class="mb-3 flex items-center justify-between">
                <div class="text-[12px] font-medium text-ink-700">分支校验条件</div>
                <button
                  type="button"
                  class="inline-flex items-center gap-1 rounded-field bg-accent px-2 py-1 text-[12px] font-semibold text-white transition hover:bg-accent-ink"
                  @click="addBranchAssertion(branch)"
                >
                  <Plus class="h-3 w-3" /> 添加校验
                </button>
              </div>
              <div
                v-for="(condition, assertionIndex) in branch.assertions"
                :key="condition.condition_id"
                class="mt-3 rounded-field border border-line p-3"
              >
                <div class="mb-2 flex items-center justify-between">
                  <span class="text-[12px] text-ink-700">校验条件 {{ assertionIndex + 1 }}</span>
                  <button
                    type="button"
                    class="ec-btn-link-danger disabled:opacity-50 disabled:cursor-not-allowed"
                    :disabled="branch.assertions.length === 1"
                    @click="removeBranchAssertion(branch, condition.condition_id)"
                  >
                    删除
                  </button>
                </div>
                <div class="grid grid-cols-2 gap-3">
                  <div>
                    <label class="mb-1 block text-[12px] text-ink-500">字段</label>
                    <el-select v-model="condition.field" class="w-full">
                      <el-option
                        v-for="field in compositeFieldOptions"
                        :key="field.value"
                        :label="field.label"
                        :value="field.value"
                      />
                    </el-select>
                  </div>
                  <div>
                    <label class="mb-1 block text-[12px] text-ink-500">校验条件</label>
                    <el-select
                      :model-value="condition.operator"
                      class="w-full"
                      @change="handleAssertionOperatorChange(condition, $event)"
                    >
                      <el-option
                        v-for="option in getConditionOptions('assertion')"
                        :key="option.value"
                        :label="option.label"
                        :value="option.value"
                      />
                    </el-select>
                  </div>
                  <div v-if="shouldShowConditionValueSource(condition)">
                    <label class="mb-1 block text-[12px] text-ink-500">右值来源</label>
                    <el-select
                      :model-value="condition.value_source ?? 'literal'"
                      class="w-full"
                      @change="handleConditionValueSourceChange(condition, $event)"
                    >
                      <el-option label="固定值" value="literal" />
                      <el-option label="字段" value="field" />
                    </el-select>
                  </div>
                  <div v-if="shouldShowConditionExpectedValue(condition)">
                    <label class="mb-1 block text-[12px] text-ink-500">比较值</label>
                    <el-input v-model="condition.expected_value" placeholder="请输入比较值" />
                  </div>
                  <div v-if="shouldShowConditionExpectedField(condition)">
                    <label class="mb-1 block text-[12px] text-ink-500">右侧字段</label>
                    <el-select v-model="condition.expected_field" class="w-full">
                      <el-option
                        v-for="field in compositeFieldOptions"
                        :key="field.value"
                        :label="field.label"
                        :value="field.value"
                      />
                    </el-select>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      <template #footer>
        <div class="flex justify-end gap-2">
          <button
            type="button"
            class="ec-btn ec-btn-secondary"
            @click="isRuleDialogVisible = false"
          >
            取消
          </button>
          <button
            type="button"
            class="ec-btn ec-btn-primary"
            @click="handleSaveRule"
          >
            保存规则
          </button>
        </div>
      </template>
    </el-dialog>
  </div>
</template>
