<script setup lang="ts">
import { computed, onMounted, reactive, ref, watch } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import {
  CircleCheckFilled,
  Delete,
  EditPen,
  Plus,
  RefreshRight,
  Search,
  VideoPlay,
} from '@element-plus/icons-vue'

import DataSourcePanel from '../components/workbench/DataSourcePanel.vue'
import SectionBlock from '../components/workbench/SectionBlock.vue'
import VariablePoolPanel from '../components/workbench/VariablePoolPanel.vue'
import { useFixedRulesStore } from '../store/fixedRules'
import type {
  CompositeAssertionOperator,
  CompositeBranch,
  CompositeCondition,
  CompositeFilterOperator,
  CompositeRuleConfig,
  FixedRuleDefinition,
  FixedRuleOperator,
  FixedRuleSelection,
} from '../types/fixedRules'
import type { DataSource, VariableTag } from '../types/workbench'

type SectionStatus = 'pending' | 'active' | 'done'
type ConditionMode = 'filter' | 'assertion'

const KEY_FIELD = '__key__'

const store = useFixedRulesStore()

const isBootstrapping = ref(true)
const isRuleDialogVisible = ref(false)
const ruleDialogMode = ref<'create' | 'edit'>('create')
const isInitializingRuleDialog = ref(false)
const isApplyingSystemRuleName = ref(false)
const isRuleNameManuallyEdited = ref(false)
const lastAutoGeneratedRuleName = ref('')

const ruleForm = reactive<{
  rule_id: string
  group_id: string
  rule_name: string
  target_variable_tag: string
  selected_rule: FixedRuleSelection
  expected_value: string
}>({
  rule_id: '',
  group_id: 'ungrouped',
  rule_name: '',
  target_variable_tag: '',
  selected_rule: 'gt',
  expected_value: '0',
})

const compositeRuleForm = reactive<CompositeRuleConfig>({
  global_filters: [],
  branches: [],
})

const ruleSelectionOptions: Array<{ label: string; value: FixedRuleSelection }> = [
  { label: '等于 (=)', value: 'eq' },
  { label: '不等于 (!=)', value: 'ne' },
  { label: '大于 (>)', value: 'gt' },
  { label: '小于 (<)', value: 'lt' },
  { label: '非空校验', value: 'not_null' },
  { label: '唯一校验', value: 'unique' },
]

const compositeFilterOptions: Array<{ label: string; value: CompositeFilterOperator }> = [
  { label: '等于 (=)', value: 'eq' },
  { label: '不等于 (!=)', value: 'ne' },
  { label: '大于 (>)', value: 'gt' },
  { label: '小于 (<)', value: 'lt' },
  { label: '非空校验', value: 'not_null' },
]

const compositeAssertionOptions: Array<{ label: string; value: CompositeAssertionOperator }> = [
  { label: '等于 (=)', value: 'eq' },
  { label: '不等于 (!=)', value: 'ne' },
  { label: '大于 (>)', value: 'gt' },
  { label: '小于 (<)', value: 'lt' },
  { label: '非空校验', value: 'not_null' },
  { label: '唯一校验', value: 'unique' },
  { label: '必须重复', value: 'duplicate_required' },
]

const compareRuleSelections = new Set<FixedRuleOperator>(['eq', 'ne', 'gt', 'lt'])
const compositeCompareOperators = new Set<CompositeFilterOperator | CompositeAssertionOperator>([
  'eq',
  'ne',
  'gt',
  'lt',
])
const ruleSelectionNameMap: Record<FixedRuleSelection, string> = {
  eq: '等于',
  ne: '不等于',
  gt: '大于',
  lt: '小于',
  not_null: '非空校验',
  unique: '唯一校验',
}
const operatorSymbolMap: Record<FixedRuleOperator, string> = {
  eq: '=',
  ne: '!=',
  gt: '>',
  lt: '<',
}

const invalidRuleIdSet = computed(() => new Set(store.invalidRuleIds))
const invalidGroupIdSet = computed(() => new Set(store.invalidGroupIds))
const variableMap = computed(
  () => new Map(store.variables.map((variable) => [variable.tag, variable] as const)),
)
const sourceMap = computed(
  () => new Map(store.sources.map((source) => [source.id, source] as const)),
)
const variableOptions = computed(() => store.variables)
const sourceIssueMap = computed(() =>
  store.configIssues.reduce<Record<string, string>>((accumulator, issue) => {
    if (issue.source_id && !accumulator[issue.source_id]) {
      accumulator[issue.source_id] = issue.message
    }
    return accumulator
  }, {}),
)
const configIssueDescription = computed(() =>
  store.configIssues.map((issue) => issue.message).join('；'),
)

const selectedRuleVariable = computed<VariableTag | null>(
  () => variableMap.value.get(ruleForm.target_variable_tag) ?? null,
)
const isCompositeRuleTarget = computed(
  () => (selectedRuleVariable.value?.variable_kind ?? 'single') === 'composite',
)
const compositeFieldOptions = computed(() => {
  const variable = selectedRuleVariable.value
  if (!variable || (variable.variable_kind ?? 'single') !== 'composite') {
    return [] as Array<{ label: string; value: string }>
  }

  const keyColumn = variable.key_column?.trim() ?? ''
  return [
    {
      label: keyColumn ? `${keyColumn} (Key)` : 'Key(映射键)',
      value: KEY_FIELD,
    },
    ...(variable.columns ?? [])
      .map((column) => column.trim())
      .filter((column) => column && column !== keyColumn)
      .map((column) => ({ label: column, value: column })),
  ]
})

const canCreateRule = computed(() => variableOptions.value.length > 0)

const shouldShowExpectedValue = computed(
  () => !isCompositeRuleTarget.value && isCompareRuleSelection(ruleForm.selected_rule),
)
const expectedValuePlaceholder = computed(() =>
  ruleForm.selected_rule === 'eq' || ruleForm.selected_rule === 'ne'
    ? '请输入要比较的精确值'
    : '请输入数值阈值',
)

const sourceStepStatus = computed<SectionStatus>(() => (store.sourceCount ? 'done' : 'active'))
const variableStepStatus = computed<SectionStatus>(() => {
  if (!store.sourceCount) {
    return 'pending'
  }
  return store.variableCount ? 'done' : 'active'
})

const sourceStepHint = computed(() =>
  store.sourceCount
    ? `已保存 ${store.sourceCount} 个数据源。`
    : '先接入数据源。',
)
const variableStepHint = computed(() => {
  if (!store.sourceCount) {
    return '请先接入数据源。'
  }
  if (!store.variableCount) {
    return '先添加变量。'
  }
  return `已保存 ${store.variableCount} 个变量。`
})

const overviewItems = computed(() => [
  { label: '数据源', value: store.sourceCount },
  { label: '变量', value: store.variableCount },
  { label: '规则总数', value: store.totalRuleCount },
  { label: '异常结果', value: store.abnormalResults.length },
])

const currentGroupCount = computed(
  () => store.groupRuleCounts[store.selectedGroup.group_id] ?? 0,
)
const currentGroupVariableCount = computed(() => {
  const tags = new Set(
    store.currentGroupRules
      .map((rule) => rule.target_variable_tag.trim())
      .filter(Boolean),
  )
  return tags.size
})

const svnResultStats = computed(() => {
  const successCount = store.svnUpdateResults.filter((item) => item.status === 'success').length
  const failedCount = store.svnUpdateResults.length - successCount
  return { successCount, failedCount }
})

const executionSummary = computed(() => {
  if (!store.executionMeta) {
    return {
      title: '执行结果',
      description: '查看扫描与异常。',
    }
  }

  return {
    title: `最近一次执行扫描 ${store.executionMeta.total_rows_scanned} 行`,
    description: `${store.executionMeta.failed_sources.length} 个失败来源，${store.abnormalResults.length} 条异常。`,
  }
})

watch(
  () => ruleForm.selected_rule,
  (selectedRule) => {
    if (!isCompareRuleSelection(selectedRule)) {
      ruleForm.expected_value = ''
      syncRuleNameWithForm()
      return
    }

    if (!ruleForm.expected_value.trim() && (selectedRule === 'gt' || selectedRule === 'lt')) {
      ruleForm.expected_value = '0'
    }

    syncRuleNameWithForm()
  },
)

watch(
  [
    () => ruleForm.target_variable_tag,
    () => ruleForm.expected_value,
  ],
  () => {
    syncRuleNameWithForm()
  },
)

watch(
  () => ruleForm.rule_name,
  (value) => {
    if (isInitializingRuleDialog.value || isApplyingSystemRuleName.value) {
      return
    }

    const normalizedValue = value.trim()
    if (!normalizedValue) {
      isRuleNameManuallyEdited.value = true
      return
    }

    isRuleNameManuallyEdited.value = normalizedValue !== lastAutoGeneratedRuleName.value
  },
)

onMounted(async () => {
  try {
    await Promise.all([store.loadCapabilities(), store.loadConfig()])
  } catch {
    // 页面级错误由 store 托管，这里避免重复提示。
  } finally {
    isBootstrapping.value = false
  }
})

function isCompareRuleSelection(value: FixedRuleSelection): value is FixedRuleOperator {
  return compareRuleSelections.has(value as FixedRuleOperator)
}

function isCompositeCompareOperator(
  value: CompositeFilterOperator | CompositeAssertionOperator,
): value is FixedRuleOperator {
  return compositeCompareOperators.has(value)
}

function createId(prefix: string): string {
  return `${prefix}-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`
}

function createCondition(): CompositeCondition {
  return {
    condition_id: createId('condition'),
    field: '',
    operator: 'eq',
    value_source: 'literal',
    expected_value: '',
    expected_field: '',
  }
}

function createBranch(): CompositeBranch {
  return {
    branch_id: createId('branch'),
    filters: [],
    assertions: [createCondition()],
  }
}

function normalizeCompositeConfig(config?: CompositeRuleConfig): CompositeRuleConfig {
  return {
    global_filters: (config?.global_filters ?? []).map((condition) => ({
      ...condition,
      condition_id: condition.condition_id || createId('condition'),
    })),
    branches: (config?.branches?.length ? config.branches : [createBranch()]).map((branch) => ({
      branch_id: branch.branch_id || createId('branch'),
      filters: (branch.filters ?? []).map((condition) => ({
        ...condition,
        condition_id: condition.condition_id || createId('condition'),
      })),
      assertions: (branch.assertions?.length ? branch.assertions : [createCondition()]).map((condition) => ({
        ...condition,
        condition_id: condition.condition_id || createId('condition'),
      })),
    })),
  }
}

function applyCompositeConfig(config?: CompositeRuleConfig): void {
  const next = normalizeCompositeConfig(config)
  compositeRuleForm.global_filters = next.global_filters
  compositeRuleForm.branches = next.branches
}

function resetCompositeConfig(): void {
  applyCompositeConfig(undefined)
}

function addGlobalFilter(): void {
  compositeRuleForm.global_filters.push(createCondition())
}

function removeGlobalFilter(conditionId: string): void {
  compositeRuleForm.global_filters = compositeRuleForm.global_filters.filter(
    (condition) => condition.condition_id !== conditionId,
  )
}

function addBranch(): void {
  compositeRuleForm.branches.push(createBranch())
}

function removeBranch(branchId: string): void {
  compositeRuleForm.branches = compositeRuleForm.branches.filter((branch) => branch.branch_id !== branchId)
}

function addBranchFilter(branch: CompositeBranch): void {
  branch.filters.push(createCondition())
}

function removeBranchFilter(branch: CompositeBranch, conditionId: string): void {
  branch.filters = branch.filters.filter((condition) => condition.condition_id !== conditionId)
}

function addBranchAssertion(branch: CompositeBranch): void {
  branch.assertions.push(createCondition())
}

function removeBranchAssertion(branch: CompositeBranch, conditionId: string): void {
  branch.assertions = branch.assertions.filter((condition) => condition.condition_id !== conditionId)
}

function setConditionOperator(
  condition: CompositeCondition,
  operator: CompositeFilterOperator | CompositeAssertionOperator,
): void {
  condition.operator = operator
  if (!isCompositeCompareOperator(operator)) {
    condition.value_source = undefined
    condition.expected_value = undefined
    condition.expected_field = undefined
    return
  }

  if (condition.value_source !== 'field' && condition.value_source !== 'literal') {
    condition.value_source = 'literal'
  }
  if (condition.value_source === 'field') {
    condition.expected_value = undefined
  } else {
    condition.expected_field = undefined
  }
}

function setConditionValueSource(condition: CompositeCondition, valueSource: 'literal' | 'field'): void {
  condition.value_source = valueSource
  if (valueSource === 'field') {
    condition.expected_value = undefined
  } else {
    condition.expected_field = undefined
  }
}

function shouldShowConditionValueSource(condition: CompositeCondition): boolean {
  return isCompositeCompareOperator(condition.operator)
}

function shouldShowConditionExpectedValue(condition: CompositeCondition): boolean {
  return isCompositeCompareOperator(condition.operator) && (condition.value_source ?? 'literal') === 'literal'
}

function shouldShowConditionExpectedField(condition: CompositeCondition): boolean {
  return isCompositeCompareOperator(condition.operator) && condition.value_source === 'field'
}

function getConditionOptions(mode: ConditionMode) {
  return mode === 'filter' ? compositeFilterOptions : compositeAssertionOptions
}

function handleFilterOperatorChange(condition: CompositeCondition, value: string): void {
  setConditionOperator(condition, value as CompositeFilterOperator)
}

function handleAssertionOperatorChange(condition: CompositeCondition, value: string): void {
  setConditionOperator(condition, value as CompositeAssertionOperator)
}

function handleConditionValueSourceChange(condition: CompositeCondition, value: string): void {
  setConditionValueSource(condition, value as 'literal' | 'field')
}

function isKnownCompositeField(field: string): boolean {
  return compositeFieldOptions.value.some((option) => option.value === field)
}

function validateCompositeCondition(
  condition: CompositeCondition,
  mode: ConditionMode,
  label: string,
): string | null {
  if (!condition.field.trim()) {
    return `${label}缺少字段。`
  }
  if (!isKnownCompositeField(condition.field.trim())) {
    return `${label}引用了当前组合变量中不存在的字段。`
  }
  if (mode === 'filter' && (condition.operator === 'unique' || condition.operator === 'duplicate_required')) {
    return `${label}的筛选条件不支持唯一或必须重复。`
  }
  if (!isCompositeCompareOperator(condition.operator)) {
    return null
  }

  if ((condition.value_source ?? 'literal') === 'field') {
    if (!condition.expected_field?.trim()) {
      return `${label}缺少右侧字段。`
    }
    if (!isKnownCompositeField(condition.expected_field.trim())) {
      return `${label}引用了无效的右侧字段。`
    }
    return null
  }

  if (!condition.expected_value?.trim()) {
    return `${label}缺少比较值。`
  }
  if ((condition.operator === 'gt' || condition.operator === 'lt') && Number.isNaN(Number(condition.expected_value))) {
    return `${label}的大于/小于比较值必须是合法数字。`
  }
  return null
}

function getSourcePath(source: DataSource | null | undefined): string {
  if (!source) {
    return ''
  }
  return source.pathOrUrl ?? source.path ?? source.url ?? ''
}

function getCompositeFieldLabel(field: string, variable: VariableTag | null): string {
  if (field !== KEY_FIELD) {
    return field
  }
  return `${variable?.key_column || 'Key'} (Key)`
}

function resolveRuleVariable(rule: FixedRuleDefinition): VariableTag | null {
  return variableMap.value.get(rule.target_variable_tag) ?? null
}

function resolveRuleSource(rule: FixedRuleDefinition): DataSource | null {
  const variable = resolveRuleVariable(rule)
  return variable ? sourceMap.value.get(variable.source_id) ?? null : null
}

function getOperatorLabel(value: FixedRuleOperator): string {
  return operatorSymbolMap[value]
}

function getRuleSelectionLabel(value: FixedRuleSelection): string {
  return ruleSelectionOptions.find((item) => item.value === value)?.label ?? value
}

function getRuleSelectionName(value: FixedRuleSelection): string {
  return ruleSelectionNameMap[value]
}

function getRuleSelectionValue(rule: FixedRuleDefinition): FixedRuleSelection {
  if (rule.rule_type === 'fixed_value_compare') {
    return rule.operator ?? 'gt'
  }
  return rule.rule_type as FixedRuleSelection
}

function getVariableColumnSummary(variable: VariableTag | null | undefined): string {
  if (!variable) {
    return '未绑定变量'
  }
  if ((variable.variable_kind ?? 'single') === 'composite') {
    return `Key=${variable.key_column || 'Key'}；成员列：${
      (variable.columns ?? [])
        .filter((column) => column !== variable.key_column)
        .join(' / ') || '未配置'
    }`
  }
  return variable.column?.trim() || '未配置列'
}

function buildVariableOptionLabel(variable: VariableTag): string {
  return `${variable.tag} | ${variable.source_id} | ${variable.sheet} | ${getVariableColumnSummary(variable)}`
}

function buildDefaultRuleName(
  variable: VariableTag | null,
  selectedRule: FixedRuleSelection,
  expectedValue: string,
): string {
  if (!variable) {
    return ''
  }

  const normalizedSheet = variable.sheet.trim()
  if ((variable.variable_kind ?? 'single') === 'composite') {
    return `${normalizedSheet}-${variable.tag}-条件分支校验`
  }
  const normalizedColumn = variable.column?.trim() ?? ''
  if (!normalizedSheet || !normalizedColumn) {
    return ''
  }

  const baseName = `${normalizedSheet}-${normalizedColumn}-${getRuleSelectionName(selectedRule)}`
  if (!isCompareRuleSelection(selectedRule)) {
    return baseName
  }

  const normalizedExpectedValue = expectedValue.trim()
  return normalizedExpectedValue ? `${baseName}+${normalizedExpectedValue}` : baseName
}

function buildDefaultRuleNameFromForm(): string {
  return buildDefaultRuleName(
    selectedRuleVariable.value,
    ruleForm.selected_rule,
    ruleForm.expected_value,
  )
}

function applySystemRuleName(nextRuleName: string): void {
  isApplyingSystemRuleName.value = true
  ruleForm.rule_name = nextRuleName
  lastAutoGeneratedRuleName.value = nextRuleName
  isRuleNameManuallyEdited.value = false
  isApplyingSystemRuleName.value = false
}

function syncRuleNameWithForm(): void {
  if (isInitializingRuleDialog.value || isRuleNameManuallyEdited.value) {
    return
  }

  const nextRuleName = buildDefaultRuleNameFromForm()
  const currentRuleName = ruleForm.rule_name.trim()
  if (!nextRuleName) {
    if (!currentRuleName || currentRuleName === lastAutoGeneratedRuleName.value) {
      applySystemRuleName('')
    }
    return
  }

  if (currentRuleName !== nextRuleName || lastAutoGeneratedRuleName.value !== nextRuleName) {
    applySystemRuleName(nextRuleName)
  }
}

function summarizeCondition(
  condition: CompositeCondition,
  variable: VariableTag | null,
): string {
  const fieldLabel = getCompositeFieldLabel(condition.field, variable)
  if (condition.operator === 'not_null') {
    return `${fieldLabel} 非空`
  }
  if (condition.operator === 'unique') {
    return `${fieldLabel} 唯一`
  }
  if (condition.operator === 'duplicate_required') {
    return `${fieldLabel} 必须重复`
  }

  const operator = {
    eq: '=',
    ne: '!=',
    gt: '>',
    lt: '<',
  }[condition.operator as FixedRuleOperator]
  const expected = condition.value_source === 'field'
    ? getCompositeFieldLabel(condition.expected_field ?? '', variable)
    : condition.expected_value ?? ''
  return `${fieldLabel} ${operator} ${expected}`
}

function buildRuleCondition(rule: FixedRuleDefinition): string {
  const variable = resolveRuleVariable(rule)
  const columnName =
    (variable?.variable_kind ?? 'single') === 'composite'
      ? variable?.tag ?? rule.target_variable_tag
      : variable?.column?.trim() || rule.target_variable_tag
  if (rule.rule_type === 'composite_condition_check') {
    const segments: string[] = []
    if (rule.composite_config?.global_filters.length) {
      segments.push(
        `全局：${rule.composite_config.global_filters
          .map((condition) => summarizeCondition(condition, variable))
          .join(' 且 ')}`,
      )
    }
    rule.composite_config?.branches.forEach((branch, index) => {
      segments.push(
        `分支 ${index + 1}：${
          branch.filters.length
            ? branch.filters.map((condition) => summarizeCondition(condition, variable)).join(' 且 ')
            : '命中全部'
        } => ${branch.assertions.map((condition) => summarizeCondition(condition, variable)).join('，')}`,
      )
    })
    return segments.join('；')
  }
  if (rule.rule_type === 'not_null') {
    return `${columnName} 非空校验`
  }
  if (rule.rule_type === 'unique') {
    return `${columnName} 唯一校验`
  }
  return `${columnName} ${getOperatorLabel(rule.operator ?? 'gt')} ${rule.expected_value ?? ''}`
}

function buildRuleSelectionSummary(rule: FixedRuleDefinition): string {
  if (rule.rule_type === 'composite_condition_check') {
    return '组合变量条件分支校验'
  }
  return getRuleSelectionLabel(getRuleSelectionValue(rule))
}

function buildRuleVariableSummary(rule: FixedRuleDefinition): string {
  const variable = resolveRuleVariable(rule)
  if (!variable) {
    return '目标变量已失效，请重新选择变量。'
  }
  return `${variable.source_id} / ${variable.sheet} / ${getVariableColumnSummary(variable)}`
}

function buildRuleSourcePathSummary(rule: FixedRuleDefinition): string {
  return getSourcePath(resolveRuleSource(rule)) || '当前数据源未记录路径'
}

async function persistConfig(successMessage?: string, silent = true): Promise<boolean> {
  try {
    await store.saveConfig()
    if (!silent && successMessage) {
      ElMessage.success(successMessage)
    }
    return true
  } catch (error) {
    ElMessage.error(error instanceof Error ? error.message : '固定规则配置保存失败。')
    return false
  }
}

async function handlePanelChanged(): Promise<void> {
  if (isBootstrapping.value) {
    return
  }
  await persistConfig(undefined, true)
}

async function handleCreateGroup(): Promise<void> {
  try {
    const result = await ElMessageBox.prompt('输入新的规则组名称。', '新建规则组', {
      confirmButtonText: '创建',
      cancelButtonText: '取消',
      inputPlaceholder: '例如：基础规则校验',
      inputValidator: (value) => Boolean(value.trim()) || '规则组名称不能为空。',
    })
    store.createGroup(result.value)
    await persistConfig('规则组已创建并保存。', false)
  } catch {
    // 用户取消时不提示。
  }
}

async function handleRenameGroup(): Promise<void> {
  if (store.selectedGroup.builtin) {
    return
  }

  try {
    const result = await ElMessageBox.prompt('修改当前规则组名称。', '编辑规则组', {
      confirmButtonText: '保存',
      cancelButtonText: '取消',
      inputValue: store.selectedGroup.group_name,
      inputValidator: (value) => Boolean(value.trim()) || '规则组名称不能为空。',
    })
    store.renameGroup(store.selectedGroup.group_id, result.value)
    await persistConfig('规则组名称已更新并保存。', false)
  } catch {
    // 用户取消时不提示。
  }
}

async function handleRemoveGroup(): Promise<void> {
  if (store.selectedGroup.builtin) {
    return
  }

  try {
    await ElMessageBox.confirm(
      `删除规则组“${store.selectedGroup.group_name}”后，组内规则会自动迁移到“未分组”。`,
      '删除规则组',
      {
        confirmButtonText: '删除',
        cancelButtonText: '取消',
        type: 'warning',
      },
    )
    store.removeGroup(store.selectedGroup.group_id)
    await persistConfig('规则组已删除，组内规则已迁移到未分组并保存。', false)
  } catch {
    // 用户取消时不提示。
  }
}

function openCreateRuleDialog(): void {
  isInitializingRuleDialog.value = true
  ruleDialogMode.value = 'create'
  ruleForm.rule_id = ''
  ruleForm.group_id = store.selectedGroup.group_id
  ruleForm.rule_name = ''
  ruleForm.target_variable_tag = variableOptions.value[0]?.tag ?? ''
  ruleForm.selected_rule = 'gt'
  ruleForm.expected_value = '0'
  resetCompositeConfig()
  isRuleNameManuallyEdited.value = false
  lastAutoGeneratedRuleName.value = ''
  isInitializingRuleDialog.value = false
  syncRuleNameWithForm()
  isRuleDialogVisible.value = true
}

function openEditRuleDialog(rule: FixedRuleDefinition): void {
  isInitializingRuleDialog.value = true
  ruleDialogMode.value = 'edit'
  ruleForm.rule_id = rule.rule_id
  ruleForm.group_id = rule.group_id
  ruleForm.rule_name = rule.rule_name
  ruleForm.target_variable_tag = rule.target_variable_tag
  if (rule.rule_type === 'composite_condition_check') {
    ruleForm.selected_rule = 'gt'
    ruleForm.expected_value = ''
    applyCompositeConfig(rule.composite_config)
  } else {
    ruleForm.selected_rule = getRuleSelectionValue(rule)
    ruleForm.expected_value = rule.expected_value ?? ''
    resetCompositeConfig()
  }
  const defaultRuleName = buildDefaultRuleName(
    resolveRuleVariable(rule),
    ruleForm.selected_rule,
    ruleForm.expected_value,
  )
  const normalizedRuleName = rule.rule_name.trim()
  isRuleNameManuallyEdited.value =
    Boolean(normalizedRuleName) && normalizedRuleName !== defaultRuleName
  lastAutoGeneratedRuleName.value = defaultRuleName
  if (!normalizedRuleName || normalizedRuleName === defaultRuleName) {
    applySystemRuleName(defaultRuleName)
  }
  isInitializingRuleDialog.value = false
  isRuleDialogVisible.value = true
}

function validateRuleForm(): boolean {
  if (!ruleForm.rule_name.trim()) {
    ElMessage.warning('规则名称不能为空。')
    return false
  }
  if (!ruleForm.target_variable_tag.trim()) {
    ElMessage.warning('请先选择目标变量。')
    return false
  }

  const variable = selectedRuleVariable.value
  if (!variable) {
    ElMessage.warning('当前目标变量不存在，请重新选择。')
    return false
  }

  if ((variable.variable_kind ?? 'single') === 'composite') {
    if (!compositeRuleForm.branches.length) {
      ElMessage.warning('组合变量规则至少需要一个条件分支。')
      return false
    }

    for (let index = 0; index < compositeRuleForm.global_filters.length; index += 1) {
      const error = validateCompositeCondition(
        compositeRuleForm.global_filters[index],
        'filter',
        `全局筛选条件 ${index + 1}`,
      )
      if (error) {
        ElMessage.warning(error)
        return false
      }
    }

    for (let branchIndex = 0; branchIndex < compositeRuleForm.branches.length; branchIndex += 1) {
      const branch = compositeRuleForm.branches[branchIndex]
      if (!branch.assertions.length) {
        ElMessage.warning(`分支 ${branchIndex + 1} 至少需要一条校验条件。`)
        return false
      }
      for (let filterIndex = 0; filterIndex < branch.filters.length; filterIndex += 1) {
        const error = validateCompositeCondition(
          branch.filters[filterIndex],
          'filter',
          `分支 ${branchIndex + 1} 的筛选条件 ${filterIndex + 1}`,
        )
        if (error) {
          ElMessage.warning(error)
          return false
        }
      }
      for (let assertionIndex = 0; assertionIndex < branch.assertions.length; assertionIndex += 1) {
        const error = validateCompositeCondition(
          branch.assertions[assertionIndex],
          'assertion',
          `分支 ${branchIndex + 1} 的校验条件 ${assertionIndex + 1}`,
        )
        if (error) {
          ElMessage.warning(error)
          return false
        }
      }
    }

    return true
  }

  if (!shouldShowExpectedValue.value) {
    return true
  }
  if (!ruleForm.expected_value.trim()) {
    ElMessage.warning('请填写比较值。')
    return false
  }
  if (
    (ruleForm.selected_rule === 'gt' || ruleForm.selected_rule === 'lt') &&
    Number.isNaN(Number(ruleForm.expected_value))
  ) {
    ElMessage.warning('大于/小于规则的比较值必须是合法数字。')
    return false
  }

  return true
}

async function handleSaveRule(): Promise<void> {
  if (!validateRuleForm()) {
    return
  }

  if (isCompositeRuleTarget.value) {
    store.upsertRule({
      rule_id: ruleForm.rule_id || undefined,
      group_id: ruleForm.group_id,
      rule_name: ruleForm.rule_name,
      target_variable_tag: ruleForm.target_variable_tag,
      rule_type: 'composite_condition_check',
      composite_config: normalizeCompositeConfig(compositeRuleForm),
    })
  } else {
    const selectedRule = ruleForm.selected_rule
    if (isCompareRuleSelection(selectedRule)) {
      store.upsertRule({
        rule_id: ruleForm.rule_id || undefined,
        group_id: ruleForm.group_id,
        rule_name: ruleForm.rule_name,
        target_variable_tag: ruleForm.target_variable_tag,
        rule_type: 'fixed_value_compare',
        operator: selectedRule,
        expected_value: ruleForm.expected_value,
      })
    } else {
      store.upsertRule({
        rule_id: ruleForm.rule_id || undefined,
        group_id: ruleForm.group_id,
        rule_name: ruleForm.rule_name,
        target_variable_tag: ruleForm.target_variable_tag,
        rule_type: selectedRule,
      })
    }
  }

  const success = await persistConfig(
    ruleDialogMode.value === 'create' ? '规则已创建并保存。' : '规则已更新并保存。',
    false,
  )
  if (success) {
    isRuleDialogVisible.value = false
  }
}

async function handleRemoveRule(rule: FixedRuleDefinition): Promise<void> {
  try {
    await ElMessageBox.confirm(`确认删除规则“${rule.rule_name}”？`, '删除规则', {
      confirmButtonText: '删除',
      cancelButtonText: '取消',
      type: 'warning',
    })
    store.removeRule(rule.rule_id)
    await persistConfig('规则已删除并保存。', false)
  } catch {
    // 用户取消时不提示。
  }
}

async function handleSaveConfig(): Promise<void> {
  await persistConfig('固定规则配置已保存。', false)
}

async function handleExecute(): Promise<void> {
  try {
    await store.executeConfig()
    if (store.abnormalResults.length) {
      ElMessage.warning(`执行完成，发现 ${store.abnormalResults.length} 条异常结果。`)
      return
    }
    ElMessage.success('执行完成，当前没有命中异常。')
  } catch {
    // 页面级错误由 store 托管。
  }
}

async function handleSvnUpdate(): Promise<void> {
  try {
    await store.runSvnUpdate()
    ElMessage.success(store.svnUpdateSummary || 'SVN 更新完成。')
  } catch {
    // 页面级错误由 store 托管。
  }
}
</script>

<template>
  <div class="fixed-rules-board rule-binding-board">
    <header class="rule-binding-header">
      <div class="rule-binding-header-main">
        <span class="guide-badge">固定规则检查</span>
        <h1>固定规则检查</h1>
        <p>本页数据独立保存。</p>
      </div>

      <div class="rule-binding-actions">
        <el-button :icon="CircleCheckFilled" plain :loading="store.isSaving" @click="handleSaveConfig">
          保存配置
        </el-button>
        <el-button
          :icon="RefreshRight"
          plain
          :loading="store.isUpdatingSvn"
          :disabled="!store.canRunSvnUpdate"
          @click="handleSvnUpdate"
        >
          SVN 更新
        </el-button>
        <el-button
          type="primary"
          :icon="VideoPlay"
          :loading="store.isExecuting"
          :disabled="!store.canExecute"
          @click="handleExecute"
        >
          执行全部规则
        </el-button>
      </div>
    </header>

    <section class="overview-strip">
      <div class="overview-grid">
        <article v-for="item in overviewItems" :key="item.label" class="overview-item">
          <div>
            <span>{{ item.label }}</span>
            <strong>{{ item.value }}</strong>
          </div>
        </article>
      </div>
      <div class="overview-actions">
        <el-tag v-if="store.config.configured" type="success" effect="light" round>
          已持久化
        </el-tag>
        <el-tag v-else type="info" effect="light" round>
          未保存
        </el-tag>
      </div>
    </section>

    <el-alert
      v-if="store.pageError"
      class="result-alert"
      type="error"
      show-icon
      :closable="false"
      :title="store.pageError"
    />

    <el-alert
      v-if="store.configIssues.length"
      class="result-alert"
      type="warning"
      show-icon
      :closable="false"
      title="存在待修复配置"
      :description="configIssueDescription"
    />

    <el-alert
      v-if="store.invalidRuleIds.length"
      class="result-alert"
      type="warning"
      show-icon
      :closable="false"
      title="存在待修复规则"
      description="补齐目标变量、规则名、比较值或分支配置后才能执行。"
    />

    <div class="rule-binding-layout" v-loading="isBootstrapping || store.isLoading">
      <SectionBlock
        step="1"
        title="数据源接入管理"
        description="录入并维护本页专用数据源。"
        :status="sourceStepStatus"
        :hint="sourceStepHint"
      >
        <DataSourcePanel
          :store="store"
          variant="fixed-rules"
          :source-issues="sourceIssueMap"
          @changed="handlePanelChanged"
        />
      </SectionBlock>

      <SectionBlock
        step="2"
        title="变量池构建"
        description="沉淀单变量和组合变量。"
        :status="variableStepStatus"
        :hint="variableStepHint"
      >
        <VariablePoolPanel :store="store" variant="fixed-rules" @changed="handlePanelChanged" />
      </SectionBlock>

      <section class="group-band-card">
        <div class="group-band-head">
          <div>
            <strong>规则组导航</strong>
            <p>管理规则分组。</p>
          </div>

          <div class="group-band-actions">
            <el-input
              v-model="store.groupKeyword"
              class="group-band-search"
              placeholder="搜索规则组"
              :prefix-icon="Search"
              clearable
            />
            <el-button :icon="Plus" plain @click="handleCreateGroup">新建规则组</el-button>
          </div>
        </div>

        <div class="group-pill-row">
          <button
            v-for="group in store.filteredGroups"
            :key="group.group_id"
            type="button"
            class="group-pill"
            :class="{ 'is-active': group.group_id === store.selectedGroup.group_id }"
            @click="store.setSelectedGroup(group.group_id)"
          >
            <div class="group-pill-main">
              <strong>{{ group.group_name }}</strong>
              <span class="group-pill-badge">
                {{ store.groupRuleCounts[group.group_id] ?? 0 }}
              </span>
            </div>
            <div class="group-pill-meta">
              <span class="group-pill-tag">
                {{ group.builtin ? '系统默认组' : '自定义组' }}
              </span>
              <span
                v-if="invalidGroupIdSet.has(group.group_id)"
                class="group-pill-tag is-danger"
              >
                待修复
              </span>
            </div>
          </button>
        </div>
      </section>

      <section class="rule-workspace-card">
        <div class="rule-workspace-head">
          <div class="rule-workspace-copy">
            <div class="rule-workspace-title">
              <strong>{{ store.selectedGroup.group_name }}</strong>
              <el-tag type="info" effect="light" round>
                当前组 {{ currentGroupCount }} 条规则
              </el-tag>
              <el-tag type="warning" effect="light" round>
                当前组 {{ currentGroupVariableCount }} 个目标变量
              </el-tag>
            </div>
            <p>单变量做基础校验，组合变量做分支校验。</p>
          </div>

          <div class="toolbar-actions">
            <el-button
              :icon="EditPen"
              plain
              :disabled="store.selectedGroup.builtin"
              @click="handleRenameGroup"
            >
              编辑组名
            </el-button>
            <el-button
              :icon="Delete"
              plain
              :disabled="store.selectedGroup.builtin"
              @click="handleRemoveGroup"
            >
              删除规则组
            </el-button>
            <el-button
              type="primary"
              :icon="Plus"
              :disabled="!canCreateRule"
              @click="openCreateRuleDialog"
            >
              新增规则
            </el-button>
          </div>
        </div>

        <div
          v-if="!canCreateRule"
          class="compact-empty-state rule-empty-state"
        >
          先在上方变量池中保存变量。
        </div>

        <div
          v-else-if="!store.currentGroupRules.length"
          class="compact-empty-state rule-empty-state"
        >
          当前规则组还没有规则。
        </div>

        <div v-else class="rule-table-shell">
          <el-table class="workbench-table" :data="store.pagedCurrentGroupRules">
            <el-table-column prop="rule_name" label="规则名称" min-width="220">
              <template #default="{ row }">
                <div class="rule-name-cell">
                  <strong :class="{ 'fixed-invalid-text': invalidRuleIdSet.has(row.rule_id) }">
                    {{ row.rule_name }}
                  </strong>
                  <span>{{ buildRuleCondition(row) }}</span>
                </div>
              </template>
            </el-table-column>

            <el-table-column label="目标变量" min-width="360">
              <template #default="{ row }">
                <div class="rule-binding-cell">
                  <div class="rule-binding-top">
                    <strong>{{ row.target_variable_tag }}</strong>
                    <span>{{ buildRuleVariableSummary(row) }}</span>
                  </div>
                  <small>{{ buildRuleSourcePathSummary(row) }}</small>
                </div>
              </template>
            </el-table-column>

            <el-table-column label="规则选择" min-width="220">
              <template #default="{ row }">
                <div class="rule-operator-cell">
                  <span>{{ buildRuleSelectionSummary(row) }}</span>
                  <strong v-if="row.rule_type === 'fixed_value_compare'">{{ row.expected_value }}</strong>
                  <strong v-else-if="row.rule_type === 'composite_condition_check'">
                    {{ row.composite_config?.branches.length ?? 0 }} 个分支
                  </strong>
                  <strong v-else>无需比较值</strong>
                </div>
              </template>
            </el-table-column>

            <el-table-column label="操作" width="160" fixed="right">
              <template #default="{ row }">
                <div class="table-actions">
                  <el-button link type="primary" @click="openEditRuleDialog(row)">编辑</el-button>
                  <el-button link type="danger" @click="handleRemoveRule(row)">删除</el-button>
                </div>
              </template>
            </el-table-column>
          </el-table>

          <div v-if="store.currentGroupRuleTotal > 20" class="fixed-pagination-row">
            <span class="pagination-caption">
              第 {{ store.currentPage }} 页 / 共 {{ store.currentGroupRuleTotal }} 条
            </span>
            <el-pagination
              layout="prev, pager, next"
              :page-size="20"
              :total="store.currentGroupRuleTotal"
              :current-page="store.currentPage"
              @current-change="store.setCurrentPage"
            />
          </div>
        </div>
      </section>

      <section class="rule-result-card">
        <div class="result-kpi-bar">
          <div class="result-kpi-main">
            <div class="result-kpi-icon">
              <CircleCheckFilled />
            </div>
            <div>
              <strong>{{ executionSummary.title }}</strong>
              <p>{{ executionSummary.description }}</p>
            </div>
          </div>

          <div class="result-kpi-progress">
            <div class="progress-caption">
              <span>执行耗时</span>
              <strong>{{ store.executionMeta?.execution_time_ms ?? 0 }} ms</strong>
            </div>
            <el-progress
              :percentage="store.executionMeta ? 100 : 0"
              :show-text="false"
              :stroke-width="8"
              status="success"
            />
          </div>

          <div class="overview-actions">
            <el-tag v-if="store.executionMeta" type="success" effect="light" round>
              已完成最近一次执行
            </el-tag>
            <el-tag v-else type="info" effect="light" round>
              等待执行
            </el-tag>
          </div>
        </div>

        <div class="result-summary">
          <article class="summary-tile">
            <span>扫描总行数</span>
            <strong>{{ store.executionMeta?.total_rows_scanned ?? 0 }}</strong>
          </article>
          <article class="summary-tile">
            <span>失败数据源</span>
            <strong>{{ store.executionMeta?.failed_sources.length ?? 0 }}</strong>
          </article>
          <article class="summary-tile">
            <span>异常结果</span>
            <strong>{{ store.abnormalResults.length }}</strong>
          </article>
          <article class="summary-tile">
            <span>固定规则数据源</span>
            <strong>{{ store.sourceCount }}</strong>
          </article>
        </div>

        <el-alert
          v-if="store.svnUpdateSummary"
          class="result-alert"
          type="info"
          show-icon
          :closable="false"
          :title="store.svnUpdateSummary"
          :description="`成功 ${svnResultStats.successCount} 个，失败 ${svnResultStats.failedCount} 个。`"
        />

        <div v-if="store.svnUpdateResults.length" class="svn-result-list">
          <article
            v-for="item in store.svnUpdateResults"
            :key="item.working_copy"
            class="svn-result-item"
            :class="{ 'is-error': item.status === 'error' }"
          >
            <strong>{{ item.working_copy }}</strong>
            <span>{{ item.status === 'success' ? '更新成功' : '更新失败' }}</span>
            <small>{{ item.output || item.error || '无额外输出' }}</small>
          </article>
        </div>

        <div v-if="!store.abnormalResults.length" class="compact-empty-state rule-empty-state">
          暂无异常。
        </div>

        <el-table v-else class="workbench-table" :data="store.abnormalResults">
          <el-table-column prop="rule_name" label="命中规则" min-width="200" />
          <el-table-column prop="location" label="定位" min-width="240" />
          <el-table-column prop="row_index" label="行号" width="100" />
          <el-table-column prop="raw_value" label="原始值" min-width="160" />
          <el-table-column prop="message" label="说明" min-width="240" />
        </el-table>
      </section>
    </div>

    <el-dialog
      v-model="isRuleDialogVisible"
      width="760px"
      :title="ruleDialogMode === 'create' ? '新增固定规则' : '编辑固定规则'"
    >
      <el-form label-position="top" class="dialog-form">
        <div class="rule-dialog-grid">
          <el-form-item label="规则组">
            <el-select v-model="ruleForm.group_id" class="full-width">
              <el-option
                v-for="group in store.allGroups"
                :key="group.group_id"
                :label="group.group_name"
                :value="group.group_id"
              />
            </el-select>
          </el-form-item>

          <el-form-item label="规则名称">
            <el-input
              v-model="ruleForm.rule_name"
              placeholder="例如：items-INT_ID-大于+0"
            />
          </el-form-item>
        </div>

        <el-form-item label="目标变量">
          <el-select
            v-model="ruleForm.target_variable_tag"
            class="full-width"
            filterable
            placeholder="选择目标变量"
          >
            <el-option
              v-for="variable in variableOptions"
              :key="variable.tag"
              :label="buildVariableOptionLabel(variable)"
              :value="variable.tag"
            />
          </el-select>
        </el-form-item>

        <div class="rule-dialog-hint">
          <span v-if="selectedRuleVariable">
            {{ selectedRuleVariable.source_id }} · {{ selectedRuleVariable.sheet }} · {{
              (selectedRuleVariable.variable_kind ?? 'single') === 'composite'
                ? getVariableColumnSummary(selectedRuleVariable)
                : selectedRuleVariable.column
            }}
          </span>
          <span v-else>
            先选目标变量。
          </span>
        </div>

        <div v-if="!isCompositeRuleTarget" class="rule-grid">
          <el-form-item label="规则选择">
            <el-select v-model="ruleForm.selected_rule" class="full-width">
              <el-option
                v-for="option in ruleSelectionOptions"
                :key="option.value"
                :label="option.label"
                :value="option.value"
              />
            </el-select>
          </el-form-item>

          <el-form-item v-if="shouldShowExpectedValue" label="比较值">
            <el-input v-model="ruleForm.expected_value" :placeholder="expectedValuePlaceholder" />
          </el-form-item>
        </div>

        <div v-else class="composite-rule-builder">
          <section class="composite-rule-section">
            <div class="composite-rule-section-head">
              <div>
                <strong>全局筛选条件</strong>
                <p>先筛记录。</p>
              </div>
              <el-button plain :icon="Plus" @click="addGlobalFilter">添加全局条件</el-button>
            </div>

            <div v-if="!compositeRuleForm.global_filters.length" class="composite-rule-empty">
              暂无全局条件。
            </div>

            <div
              v-for="(condition, index) in compositeRuleForm.global_filters"
              :key="condition.condition_id"
              class="composite-condition-card"
            >
              <div class="composite-condition-head">
                <strong>全局条件 {{ index + 1 }}</strong>
                <el-button link type="danger" @click="removeGlobalFilter(condition.condition_id)">
                  删除
                </el-button>
              </div>
              <div class="composite-condition-grid">
                <el-form-item label="字段">
                  <el-select v-model="condition.field" class="full-width">
                    <el-option
                      v-for="field in compositeFieldOptions"
                      :key="field.value"
                      :label="field.label"
                      :value="field.value"
                    />
                  </el-select>
                </el-form-item>

                <el-form-item label="筛选条件">
                  <el-select
                    :model-value="condition.operator"
                    class="full-width"
                    @change="handleFilterOperatorChange(condition, $event)"
                  >
                    <el-option
                      v-for="option in getConditionOptions('filter')"
                      :key="option.value"
                      :label="option.label"
                      :value="option.value"
                    />
                  </el-select>
                </el-form-item>

                <el-form-item v-if="shouldShowConditionValueSource(condition)" label="右值来源">
                  <el-select
                    :model-value="condition.value_source ?? 'literal'"
                    class="full-width"
                    @change="handleConditionValueSourceChange(condition, $event)"
                  >
                    <el-option label="固定值" value="literal" />
                    <el-option label="字段" value="field" />
                  </el-select>
                </el-form-item>

                <el-form-item v-if="shouldShowConditionExpectedValue(condition)" label="比较值">
                  <el-input v-model="condition.expected_value" placeholder="请输入比较值" />
                </el-form-item>

                <el-form-item v-if="shouldShowConditionExpectedField(condition)" label="右侧字段">
                  <el-select v-model="condition.expected_field" class="full-width">
                    <el-option
                      v-for="field in compositeFieldOptions"
                      :key="field.value"
                      :label="field.label"
                      :value="field.value"
                    />
                  </el-select>
                </el-form-item>
              </div>
            </div>
          </section>

          <section class="composite-rule-section">
            <div class="composite-rule-section-head">
              <div>
                <strong>条件分支列表</strong>
                <p>命中后再校验。</p>
              </div>
              <el-button type="primary" plain :icon="Plus" @click="addBranch">添加分支</el-button>
            </div>

            <div
              v-for="(branch, branchIndex) in compositeRuleForm.branches"
              :key="branch.branch_id"
              class="composite-branch-card"
            >
              <div class="composite-condition-head">
                <div>
                  <strong>分支 {{ branchIndex + 1 }}</strong>
                  <p>命中后校验。</p>
                </div>
                <el-button link type="danger" @click="removeBranch(branch.branch_id)">删除分支</el-button>
              </div>

              <div class="composite-branch-section">
                <div class="composite-rule-subhead">
                  <strong>分支筛选条件</strong>
                  <el-button plain @click="addBranchFilter(branch)">添加筛选条件</el-button>
                </div>
                <div v-if="!branch.filters.length" class="composite-rule-empty">
                  暂无分支条件。
                </div>
                <div
                  v-for="(condition, filterIndex) in branch.filters"
                  :key="condition.condition_id"
                  class="composite-condition-card is-nested"
                >
                  <div class="composite-condition-head">
                    <strong>筛选条件 {{ filterIndex + 1 }}</strong>
                    <el-button link type="danger" @click="removeBranchFilter(branch, condition.condition_id)">
                      删除
                    </el-button>
                  </div>
                  <div class="composite-condition-grid">
                    <el-form-item label="字段">
                      <el-select v-model="condition.field" class="full-width">
                        <el-option
                          v-for="field in compositeFieldOptions"
                          :key="field.value"
                          :label="field.label"
                          :value="field.value"
                        />
                      </el-select>
                    </el-form-item>

                    <el-form-item label="筛选条件">
                      <el-select
                        :model-value="condition.operator"
                        class="full-width"
                        @change="handleFilterOperatorChange(condition, $event)"
                      >
                        <el-option
                          v-for="option in getConditionOptions('filter')"
                          :key="option.value"
                          :label="option.label"
                          :value="option.value"
                        />
                      </el-select>
                    </el-form-item>

                    <el-form-item v-if="shouldShowConditionValueSource(condition)" label="右值来源">
                      <el-select
                        :model-value="condition.value_source ?? 'literal'"
                        class="full-width"
                        @change="handleConditionValueSourceChange(condition, $event)"
                      >
                        <el-option label="固定值" value="literal" />
                        <el-option label="字段" value="field" />
                      </el-select>
                    </el-form-item>

                    <el-form-item v-if="shouldShowConditionExpectedValue(condition)" label="比较值">
                      <el-input v-model="condition.expected_value" placeholder="请输入比较值" />
                    </el-form-item>

                    <el-form-item v-if="shouldShowConditionExpectedField(condition)" label="右侧字段">
                      <el-select v-model="condition.expected_field" class="full-width">
                        <el-option
                          v-for="field in compositeFieldOptions"
                          :key="field.value"
                          :label="field.label"
                          :value="field.value"
                        />
                      </el-select>
                    </el-form-item>
                  </div>
                </div>
              </div>

              <div class="composite-branch-section">
                <div class="composite-rule-subhead">
                  <strong>分支校验条件</strong>
                  <el-button type="primary" plain @click="addBranchAssertion(branch)">添加校验条件</el-button>
                </div>
                <div class="composite-rule-empty">
                  支持比较 / 唯一 / 必须重复。
                </div>
                <div
                  v-for="(condition, assertionIndex) in branch.assertions"
                  :key="condition.condition_id"
                  class="composite-condition-card is-nested"
                >
                  <div class="composite-condition-head">
                    <strong>校验条件 {{ assertionIndex + 1 }}</strong>
                    <el-button
                      link
                      type="danger"
                      :disabled="branch.assertions.length === 1"
                      @click="removeBranchAssertion(branch, condition.condition_id)"
                    >
                      删除
                    </el-button>
                  </div>
                  <div class="composite-condition-grid">
                    <el-form-item label="字段">
                      <el-select v-model="condition.field" class="full-width">
                        <el-option
                          v-for="field in compositeFieldOptions"
                          :key="field.value"
                          :label="field.label"
                          :value="field.value"
                        />
                      </el-select>
                    </el-form-item>

                    <el-form-item label="校验条件">
                      <el-select
                        :model-value="condition.operator"
                        class="full-width"
                        @change="handleAssertionOperatorChange(condition, $event)"
                      >
                        <el-option
                          v-for="option in getConditionOptions('assertion')"
                          :key="option.value"
                          :label="option.label"
                          :value="option.value"
                        />
                      </el-select>
                    </el-form-item>

                    <el-form-item v-if="shouldShowConditionValueSource(condition)" label="右值来源">
                      <el-select
                        :model-value="condition.value_source ?? 'literal'"
                        class="full-width"
                        @change="handleConditionValueSourceChange(condition, $event)"
                      >
                        <el-option label="固定值" value="literal" />
                        <el-option label="字段" value="field" />
                      </el-select>
                    </el-form-item>

                    <el-form-item v-if="shouldShowConditionExpectedValue(condition)" label="比较值">
                      <el-input v-model="condition.expected_value" placeholder="请输入比较值" />
                    </el-form-item>

                    <el-form-item v-if="shouldShowConditionExpectedField(condition)" label="右侧字段">
                      <el-select v-model="condition.expected_field" class="full-width">
                        <el-option
                          v-for="field in compositeFieldOptions"
                          :key="field.value"
                          :label="field.label"
                          :value="field.value"
                        />
                      </el-select>
                    </el-form-item>
                  </div>
                </div>
              </div>
            </div>
          </section>
        </div>
      </el-form>

      <template #footer>
        <div class="dialog-footer">
          <el-button @click="isRuleDialogVisible = false">取消</el-button>
          <el-button type="primary" @click="handleSaveRule">保存规则</el-button>
        </div>
      </template>
    </el-dialog>
  </div>
</template>
